
* 1. Nothing but the Truth
This is a clojure form.  Enter a value which will make the form evaluate to true.  Don't over think it!  If you are confused, see the [getting started]('/directions') page.  Hint: true is equal to true.
#+begin_src clojure
(def __ )
(= __ true)
#+end_src
* 2. Simple Math
If you are not familiar with [polish notation]('http://en.wikipedia.org/wiki/Polish_notation'), simple arithmetic might seem confusing.**Note:** Enter only enough to fill in the blank (in this case, a single number) - do not retype the whole problem.
#+begin_src clojure
(def __ )
(= (- 10 (* 2 3)) __)
#+end_src
* 3. Intro to Strings
Clojure strings are Java strings.  This means that you can use any of the Java string methods on Clojure strings.
#+begin_src clojure
(def __ )
(= __ (.toUpperCase "hello world"))
#+end_src
* 4. Intro to Lists
Lists can be constructed with either a function or a quoted form.
#+begin_src clojure
(def __ )
(= (list __) '(:a :b :c))
#+end_src
* 6. Intro to Vectors
Vectors can be constructed several ways.  You can compare them with lists.   
<br/>

**Note**: the brackets [] surrounding the blanks __ are part of the test case.
#+begin_src clojure
(def __ )
(= [__] (list :a :b :c) (vec '(:a :b :c)) (vector :a :b :c))
#+end_src
* 7. Vectors: conj
When operating on a Vector, the conj function will return a new vector with one or more items "added" to the end.
#+begin_src clojure
(def __ )
(= __ (conj [1 2 3] 4))
(= __ (conj [1 2] 3 4))
#+end_src
* 8. Intro to Sets
Sets are collections of unique values.
#+begin_src clojure
(def __ )
(= __ (set '(:a :a :b :c :c :c :c :d :d)))
(= __ (clojure.set/union #{:a :b :c} #{:b :c :d}))
#+end_src
* 9. Sets: conj
When operating on a set, the conj function returns a new set with one or more keys "added".
#+begin_src clojure
(def __ )
(= #{1 2 3 4} (conj #{1 4 3} __))
#+end_src
* 10. Intro to Maps
Maps store key-value pairs.  Both maps and keywords can be used as lookup functions. Commas can be used to make maps more readable, but they are not required.
#+begin_src clojure
(def __ )
(= __ ((hash-map :a 10, :b 20, :c 30) :b))
(= __ (:b {:a 10, :b 20, :c 30}))
#+end_src
* 11. Maps: conj
When operating on a map, the conj function returns a new map with one or more key-value pairs "added".
#+begin_src clojure
(def __ )
(= {:a 1, :b 2, :c 3} (conj {:a 1} __ [:c 3]))
#+end_src
* 12. Intro to Sequences
All Clojure collections support sequencing.  You can operate on sequences with functions like first, second, and last.
#+begin_src clojure
(def __ )
(= __ (first '(3 2 1)))
(= __ (second [2 3 4]))
(= __ (last (list 1 2 3)))
#+end_src
* 13. Sequences: rest
The rest function will return all the items of a sequence except the first.
#+begin_src clojure
(def __ )
(= __ (rest [10 20 30 40]))
#+end_src
* 14. Intro to Functions
Clojure has many different ways to create functions.
#+begin_src clojure
(def __ )
(= __ ((fn add-five [x] (+ x 5)) 3))
(= __ ((fn [x] (+ x 5)) 3))
(= __ (#(+ % 5) 3))
(= __ ((partial + 5) 3))
#+end_src
* 15. Double Down
Write a function which doubles a number.
#+begin_src clojure
(def __ )
(= (__ 2) 4)
(= (__ 3) 6)
(= (__ 11) 22)
(= (__ 7) 14)
#+end_src
* 16. Hello World
Write a function which returns a personalized greeting.
#+begin_src clojure
(def __ )
(= (__ "Dave") "Hello, Dave!")
(= (__ "Jenn") "Hello, Jenn!")
(= (__ "Rhea") "Hello, Rhea!")
#+end_src
* 17. Sequences: map
The map function takes two arguments: a function (f) and a sequence (s).  Map returns a new sequence consisting of the result of applying f to each item of s.  Do not confuse the map function with the map data structure.
#+begin_src clojure
(def __ )
(= __ (map #(+ % 5) '(1 2 3)))
#+end_src
* 18. Sequences: filter
The filter function takes two arguments: a predicate function (f) and a sequence (s).  Filter returns a new sequence consisting of all the items of s for which (f item) returns true.
#+begin_src clojure
(def __ )
(= __ (filter #(> % 5) '(3 4 5 6 7)))
#+end_src
* 19. Last Element
Write a function which returns the last element in a sequence.
#+begin_src clojure
(def __ )
(= (__ [1 2 3 4 5]) 5)
(= (__ '(5 4 3)) 3)
(= (__ ["b" "c" "d"]) "d")
#+end_src
* 20. Penultimate Element
Write a function which returns the second to last element from a sequence.
#+begin_src clojure
(def __ )
(= (__ (list 1 2 3 4 5)) 4)
(= (__ ["a" "b" "c"]) "b")
(= (__ [[1 2] [3 4]]) [1 2])
#+end_src
* 21. Nth Element
Write a function which returns the Nth element from a sequence.
#+begin_src clojure
(def __ )
(= (__ '(4 5 6 7) 2) 6)
(= (__ [:a :b :c] 0) :a)
(= (__ [1 2 3 4] 1) 2)
(= (__ '([1 2] [3 4] [5 6]) 2) [5 6])
#+end_src
* 22. Count a Sequence
Write a function which returns the total number of elements in a sequence.
#+begin_src clojure
(def __ )
(= (__ '(1 2 3 3 1)) 5)
(= (__ "Hello World") 11)
(= (__ [[1 2] [3 4] [5 6]]) 3)
(= (__ '(13)) 1)
(= (__ '(:a :b :c)) 3)
#+end_src
* 23. Reverse a Sequence
Write a function which reverses a sequence.
#+begin_src clojure
(def __ )
(= (__ [1 2 3 4 5]) [5 4 3 2 1])
(= (__ (sorted-set 5 7 2 7)) '(7 5 2))
(= (__ [[1 2][3 4][5 6]]) [[5 6][3 4][1 2]])
#+end_src
* 24. Sum It All Up
Write a function which returns the sum of a sequence of numbers.
#+begin_src clojure
(def __ )
(= (__ [1 2 3]) 6)
(= (__ (list 0 -2 5 5)) 8)
(= (__ #{4 2 1}) 7)
(= (__ '(0 0 -1)) -1)
(= (__ '(1 10 3)) 14)
#+end_src
* 25. Find the odd numbers
Write a function which returns only the odd numbers from a sequence.
#+begin_src clojure
(def __ )
(= (__ #{1 2 3 4 5}) '(1 3 5))
(= (__ [4 2 1 6]) '(1))
(= (__ [2 2 4 6]) '())
(= (__ [1 1 1 3]) '(1 1 1 3))
#+end_src
* 26. Fibonacci Sequence
Write a function which returns the first X fibonacci numbers.
#+begin_src clojure
(def __ )
(= (__ 3) '(1 1 2))
(= (__ 6) '(1 1 2 3 5 8))
(= (__ 8) '(1 1 2 3 5 8 13 21))
#+end_src
* 27. Palindrome Detector
Write a function which returns true if the given sequence is a palindrome.  
<br>
Hint: "racecar" does not equal '(\r \a \c \e \c \a \r)
#+begin_src clojure
(def __ )
(false? (__ '(1 2 3 4 5)))
(true? (__ "racecar"))
(true? (__ [:foo :bar :foo]))
(true? (__ '(1 1 3 3 1 1)))
(false? (__ '(:a :b :c)))
#+end_src
* 28. Flatten a Sequence
Write a function which flattens a sequence.
#+begin_src clojure
(def __ )
(= (__ '((1 2) 3 [4 [5 6]])) '(1 2 3 4 5 6))
(= (__ ["a" ["b"] "c"]) '("a" "b" "c"))
(= (__ '((((:a))))) '(:a))
#+end_src
* 29. Get the Caps
Write a function which takes a string and returns a new string containing only the capital letters.
#+begin_src clojure
(def __ )
(= (__ "HeLlO, WoRlD!") "HLOWRD")
(empty? (__ "nothing"))
(= (__ "$#A(*&987Zf") "AZ")
#+end_src
* 30. Compress a Sequence
Write a function which removes consecutive duplicates from a sequence.
#+begin_src clojure
(def __ )
(= (apply str (__ "Leeeeeerrroyyy")) "Leroy")
(= (__ [1 1 2 3 3 2 2 3]) '(1 2 3 2 3))
(= (__ [[1 2] [1 2] [3 4] [1 2]]) '([1 2] [3 4] [1 2]))
#+end_src
* 31. Pack a Sequence
Write a function which packs consecutive duplicates into sub-lists.
#+begin_src clojure
(def __ )
(= (__ [1 1 2 1 1 1 3 3]) '((1 1) (2) (1 1 1) (3 3)))
(= (__ [:a :a :b :b :c]) '((:a :a) (:b :b) (:c)))
(= (__ [[1 2] [1 2] [3 4]]) '(([1 2] [1 2]) ([3 4])))
#+end_src
* 32. Duplicate a Sequence
Write a function which duplicates each element of a sequence.
#+begin_src clojure
(def __ )
(= (__ [1 2 3]) '(1 1 2 2 3 3))
(= (__ [:a :a :b :b]) '(:a :a :a :a :b :b :b :b))
(= (__ [[1 2] [3 4]]) '([1 2] [1 2] [3 4] [3 4]))
(= (__ [[1 2] [3 4]]) '([1 2] [1 2] [3 4] [3 4]))
#+end_src
* 33. Replicate a Sequence
Write a function which replicates each element of a sequence a variable number of times.
#+begin_src clojure
(def __ )
(= (__ [1 2 3] 2) '(1 1 2 2 3 3))
(= (__ [:a :b] 4) '(:a :a :a :a :b :b :b :b))
(= (__ [4 5 6] 1) '(4 5 6))
(= (__ [[1 2] [3 4]] 2) '([1 2] [1 2] [3 4] [3 4]))
(= (__ [44 33] 2) [44 44 33 33])
#+end_src
* 34. Implement range
Write a function which creates a list of all integers in a given range.
#+begin_src clojure
(def __ )
(= (__ 1 4) '(1 2 3))
(= (__ -2 2) '(-2 -1 0 1))
(= (__ 5 8) '(5 6 7))
#+end_src
* 35. Local bindings
Clojure lets you give local names to values using the special let-form.
#+begin_src clojure
(def __ )
(= __ (let [x 5] (+ 2 x)))
(= __ (let [x 3, y 10] (- y x)))
(= __ (let [x 21] (let [y 3] (/ x y))))
#+end_src
* 36. Let it Be
Can you bind x, y, and z so that these are all true?
#+begin_src clojure
(def __ )
(= 10 (let __ (+ x y)))
(= 4 (let __ (+ y z)))
(= 1 (let __ z))
#+end_src
* 37. Regular Expressions
Regex patterns are supported with a special reader macro.
#+begin_src clojure
(def __ )
(= __ (apply str (re-seq #"[A-Z]+" "bA1B3Ce ")))
#+end_src
* 38. Maximum value
Write a function which takes a variable number of parameters and returns the maximum value.
#+begin_src clojure
(def __ )
(= (__ 1 8 3 4) 8)
(= (__ 30 20) 30)
(= (__ 45 67 11) 67)
#+end_src
* 39. Interleave Two Seqs
Write a function which takes two sequences and returns the first item from each, then the second item from each, then the third, etc.
#+begin_src clojure
(def __ )
(= (__ [1 2 3] [:a :b :c]) '(1 :a 2 :b 3 :c))
(= (__ [1 2] [3 4 5 6]) '(1 3 2 4))
(= (__ [1 2 3 4] [5]) [1 5])
(= (__ [30 20] [25 15]) [30 25 20 15])
#+end_src
* 40. Interpose a Seq
Write a function which separates the items of a sequence by an arbitrary value.
#+begin_src clojure
(def __ )
(= (__ 0 [1 2 3]) [1 0 2 0 3])
(= (apply str (__ ", " ["one" "two" "three"])) "one, two, three")
(= (__ :z [:a :b :c :d]) [:a :z :b :z :c :z :d])
#+end_src
* 41. Drop Every Nth Item
Write a function which drops every Nth item from a sequence.
#+begin_src clojure
(def __ )
(= (__ [1 2 3 4 5 6 7 8] 3) [1 2 4 5 7 8])
(= (__ [:a :b :c :d :e :f] 2) [:a :c :e])
(= (__ [1 2 3 4 5 6] 4) [1 2 3 5 6])
#+end_src
* 42. Factorial Fun
Write a function which calculates factorials.
#+begin_src clojure
(def __ )
(= (__ 1) 1)
(= (__ 3) 6)
(= (__ 5) 120)
(= (__ 8) 40320)
#+end_src
* 43. Reverse Interleave
Write a function which reverses the interleave process into x number of subsequences.
#+begin_src clojure
(def __ )
(= (__ [1 2 3 4 5 6] 2) '((1 3 5) (2 4 6)))
(= (__ (range 9) 3) '((0 3 6) (1 4 7) (2 5 8)))
(= (__ (range 10) 5) '((0 5) (1 6) (2 7) (3 8) (4 9)))
#+end_src
* 44. Rotate Sequence
Write a function which can rotate a sequence in either direction.
#+begin_src clojure
(def __ )
(= (__ 2 [1 2 3 4 5]) '(3 4 5 1 2))
(= (__ -2 [1 2 3 4 5]) '(4 5 1 2 3))
(= (__ 6 [1 2 3 4 5]) '(2 3 4 5 1))
(= (__ 1 '(:a :b :c)) '(:b :c :a))
(= (__ -4 '(:a :b :c)) '(:c :a :b))
#+end_src
* 45. Intro to Iterate
The iterate function can be used to produce an infinite lazy sequence.
#+begin_src clojure
(def __ )
(= __ (take 5 (iterate #(+ 3 %) 1)))
#+end_src
* 46. Flipping out
Write a higher-order function which flips the order of the arguments of an input function.
#+begin_src clojure
(def __ )
(= 3 ((__ nth) 2 [1 2 3 4 5]))
(= true ((__ >) 7 8))
(= 4 ((__ quot) 2 8))
(= [1 2 3] ((__ take) [1 2 3 4 5] 3))
#+end_src
* 47. Contain Yourself
The contains? function checks if a KEY is present in a given collection.  This often leads beginner clojurians to use it incorrectly with numerically indexed collections like vectors and lists.
#+begin_src clojure
(def __ )
(contains? #{4 5 6} __)
(contains? [1 1 1 1 1] __)
(contains? {4 :a 2 :b} __)
(not (contains? [1 2 4] __))
#+end_src
* 48. Intro to some
The some function takes a predicate function and a collection.  It returns the first logical true value of (predicate x) where x is an item in the collection.
#+begin_src clojure
(def __ )
(= __ (some #{2 7 6} [5 6 7 8]))
(= __ (some #(when (even? %) %) [5 6 7 8]))
#+end_src
* 49. Split a sequence
Write a function which will split a sequence into two parts.
#+begin_src clojure
(def __ )
(= (__ 3 [1 2 3 4 5 6]) [[1 2 3] [4 5 6]])
(= (__ 1 [:a :b :c :d]) [[:a] [:b :c :d]])
(= (__ 2 [[1 2] [3 4] [5 6]]) [[[1 2] [3 4]] [[5 6]]])
#+end_src
* 50. Split by Type
Write a function which takes a sequence consisting of items with different types and splits them up into a set of homogeneous sub-sequences. The internal order of each sub-sequence should be maintained, but the sub-sequences themselves can be returned in any order (this is why 'set' is used in the test cases).
#+begin_src clojure
(def __ )
(= (set (__ [1 :a 2 :b 3 :c])) #{[1 2 3] [:a :b :c]})
(= (set (__ [:a "foo"  "bar" :b])) #{[:a :b] ["foo" "bar"]})
(= (set (__ [[1 2] :a [3 4] 5 6 :b])) #{[[1 2] [3 4]] [:a :b] [5 6]})
#+end_src
* 51. Advanced Destructuring
Here is an example of some more sophisticated destructuring.
#+begin_src clojure
(def __ )
(= [1 2 [3 4 5] [1 2 3 4 5]] (let [[a b & c :as d] __] [a b c d]))
#+end_src
* 52. Intro to Destructuring
Let bindings and function parameter lists support destructuring.
#+begin_src clojure
(def __ )
(= [2 4] (let [[a b c d e] [0 1 2 3 4]] __))
#+end_src
* 53. Longest Increasing Sub-Seq
Given a vector of integers, find the longest consecutive sub-sequence of increasing numbers. If two sub-sequences have the same length, use the one that occurs first. An increasing sub-sequence must have a length of 2 or greater to qualify.
#+begin_src clojure
(def __ )
(= (__ [1 0 1 2 3 0 4 5]) [0 1 2 3])
(= (__ [5 6 1 3 2 7]) [5 6])
(= (__ [2 3 3 4 5]) [3 4 5])
(= (__ [7 6 5 4]) [])
#+end_src
* 54. Partition a Sequence
Write a function which returns a sequence of lists of x items each.  Lists of less than x items should not be returned.
#+begin_src clojure
(def __ )
(= (__ 3 (range 9)) '((0 1 2) (3 4 5) (6 7 8)))
(= (__ 2 (range 8)) '((0 1) (2 3) (4 5) (6 7)))
(= (__ 3 (range 8)) '((0 1 2) (3 4 5)))
#+end_src
* 55. Count Occurrences
Write a function which returns a map containing the number of occurences of each distinct item in a sequence.
#+begin_src clojure
(def __ )
(= (__ [1 1 2 3 2 1 1]) {1 4, 2 2, 3 1})
(= (__ [:b :a :b :a :b]) {:a 2, :b 3})
(= (__ '([1 2] [1 3] [1 3])) {[1 2] 1, [1 3] 2})
#+end_src
* 56. Find Distinct Items
Write a function which removes the duplicates from a sequence. Order of the items must be maintained.
#+begin_src clojure
(def __ )
(= (__ [1 2 1 3 1 2 4]) [1 2 3 4])
(= (__ [:a :a :b :b :c :c]) [:a :b :c])
(= (__ '([2 4] [1 2] [1 3] [1 3])) '([2 4] [1 2] [1 3]))
(= (__ (range 50)) (range 50))
#+end_src
* 57. Simple Recursion
A recursive function is a function which calls itself.  This is one of the fundamental techniques used in functional programming.
#+begin_src clojure
(def __ )
(= __ ((fn foo [x] (when (> x 0) (conj (foo (dec x)) x))) 5))
#+end_src
* 58. Function Composition
Write a function which allows you to create function compositions.  The parameter list should take a variable number of functions, and create a function that applies them from right-to-left.
#+begin_src clojure
(def __ )
(= [3 2 1] ((__ rest reverse) [1 2 3 4]))
(= 5 ((__ (partial + 3) second) [1 2 3 4]))
(= true ((__ zero? #(mod % 8) +) 3 5 7 9))
(= "HELLO" ((__ #(.toUpperCase %) #(apply str %) take) 5 "hello world"))
#+end_src
* 59. Juxtaposition
Take a set of functions and return a new function that takes a variable number of arguments and returns a sequence containing the result of applying each function left-to-right to the argument list.
#+begin_src clojure
(def __ )
(= [21 6 1] ((__ + max min) 2 3 5 1 6 4))
(= ["HELLO" 5] ((__ #(.toUpperCase %) count) "hello"))
(= [2 6 4] ((__ :a :c :b) {:a 2, :b 4, :c 6, :d 8 :e 10}))
#+end_src
* 60. Sequence Reductions
Write a function which behaves like reduce, but returns each intermediate value of the reduction.  Your function must accept either two or three arguments, and the return sequence must be lazy.
#+begin_src clojure
(def __ )
(= (take 5 (__ + (range))) [0 1 3 6 10])
(= (__ conj [1] [2 3 4]) [[1] [1 2] [1 2 3] [1 2 3 4]])
(= (last (__ * 2 [3 4 5])) (reduce * 2 [3 4 5]) 120)
#+end_src
* 61. Map Construction
Write a function which takes a vector of keys and a vector of values and constructs a map from them.
#+begin_src clojure
(def __ )
(= (__ [:a :b :c] [1 2 3]) {:a 1, :b 2, :c 3})
(= (__ [1 2 3 4] ["one" "two" "three"]) {1 "one", 2 "two", 3 "three"})
(= (__ [:foo :bar] ["foo" "bar" "baz"]) {:foo "foo", :bar "bar"})
#+end_src
* 62. Re-implement Iterate
Given a side-effect free function f and an initial value x write a function which returns an infinite lazy sequence of x, (f x), (f (f x)), (f (f (f x))), etc.
#+begin_src clojure
(def __ )
(= (take 5 (__ #(* 2 %) 1)) [1 2 4 8 16])
(= (take 100 (__ inc 0)) (take 100 (range)))
(= (take 9 (__ #(inc (mod % 3)) 1)) (take 9 (cycle [1 2 3])))
#+end_src
* 63. Group a Sequence
Given a function f and a sequence s, write a function which returns a map.  The keys should be the values of f applied to each item in s.  The value at each key should be a vector of corresponding items in the order they appear in s.
#+begin_src clojure
(def __ )
(= (__ #(> % 5) [1 3 6 8]) {false [1 3], true [6 8]})
(= (__ #(apply / %) [[1 2] [2 4] [4 6] [3 6]])
   {1/2 [[1 2] [2 4] [3 6]], 2/3 [[4 6]]})
(= (__ count [[1] [1 2] [3] [1 2 3] [2 3]])
   {1 [[1] [3]], 2 [[1 2] [2 3]], 3 [[1 2 3]]})
#+end_src
* 64. Intro to Reduce
[Reduce]('http://clojuredocs.org/clojure_core/clojure.core/reduce') takes a 2 argument function and an optional starting value. It then applies the function to the first 2 items in the sequence (or the starting value and the first element of the sequence). In the next iteration the function will be called on the previous return value and the next item from the sequence, thus reducing the entire collection to one value. Don't worry, it's not as complicated as it sounds.
#+begin_src clojure
(def __ )
(= 15 (reduce __ [1 2 3 4 5]))
(=  0 (reduce __ []))
(=  6 (reduce __ 1 [2 3]))
#+end_src
* 65. Black Box Testing
Clojure has many sequence types, which act in subtly different ways. The core functions typically convert them into a uniform "sequence" type and work with them that way, but it can be important to understand the behavioral and performance differences so that you know which kind is appropriate for your application.  
<br />

Write a function which takes a collection and returns one of :map, :set, :list, or :vector - describing the type of collection it was given.  
You won't be allowed to inspect their class or use the built-in predicates like list? - the point is to poke at them and understand their behavior.
#+begin_src clojure
(def __ )
(= :map (__ {:a 1, :b 2}))
(= :list (__ (range (rand-int 20))))
(= :vector (__ [1 2 3 4 5 6]))
(= :set (__ #{10 (rand-int 5)}))
(= [:map :set :vector :list] (map __ [{} #{} [] ()]))
#+end_src
* 66. Greatest Common Divisor
Given two integers, write a function which returns the greatest common divisor.
#+begin_src clojure
(def __ )
(= (__ 2 4) 2)
(= (__ 10 5) 5)
(= (__ 5 7) 1)
(= (__ 1023 858) 33)
#+end_src
* 67. Prime Numbers
Write a function which returns the first x number of prime numbers.
#+begin_src clojure
(def __ )
(= (__ 2) [2 3])
(= (__ 5) [2 3 5 7 11])
(= (last (__ 100)) 541)
#+end_src
* 68. Recurring Theme
Clojure only has one non-stack-consuming looping construct: recur.  Either a function or a loop can be used as the recursion point.  Either way, recur rebinds the bindings of the recursion point to the values it is passed.  Recur must be called from the tail-position, and calling it elsewhere will result in an error.
#+begin_src clojure
(def __ )
(= __
  (loop [x 5
         result []]
    (if (> x 0)
      (recur (dec x) (conj result (+ 2 x)))
      result)))
#+end_src
* 69. Merge with a Function
Write a function which takes a function f and a variable number of maps.  Your function should return a map that consists of the rest of the maps conj-ed onto the first.  If a key occurs in more than one map, the mapping(s) from the latter (left-to-right) should be combined with the mapping in the result by calling (f val-in-result val-in-latter)
#+begin_src clojure
(def __ )
(= (__ * {:a 2, :b 3, :c 4} {:a 2} {:b 2} {:c 5})
   {:a 4, :b 6, :c 20})
(= (__ - {1 10, 2 20} {1 3, 2 10, 3 15})
   {1 7, 2 10, 3 15})
(= (__ concat {:a [3], :b [6]} {:a [4 5], :c [8 9]} {:b [7]})
   {:a [3 4 5], :b [6 7], :c [8 9]})
#+end_src
* 70. Word Sorting
Write a function that splits a sentence up into a sorted list of words.  Capitalization should not affect sort order and punctuation should be ignored.
#+begin_src clojure
(def __ )
(= (__  "Have a nice day.")
   ["a" "day" "Have" "nice"])
(= (__  "Clojure is a fun language!")
   ["a" "Clojure" "fun" "is" "language"])
(= (__  "Fools fall for foolish follies.")
   ["fall" "follies" "foolish" "Fools" "for"])
#+end_src
* 71. Rearranging Code: ->
The -> macro threads an expression x through a variable number of forms. First, x is inserted as the second item in the first form, making a list of it if it is not a list already.  Then the first form is inserted as the second item in the second form, making a list of that form if necessary.  This process continues for all the forms.  Using -> can sometimes make your code more readable.
#+begin_src clojure
(def __ )
(= (__ (sort (rest (reverse [2 5 4 1 3 6]))))
   (-> [2 5 4 1 3 6] (reverse) (rest) (sort) (__))
   5)
#+end_src
* 72. Rearranging Code: ->>
The ->> macro threads an expression x through a variable number of forms. First, x is inserted as the last item in the first form, making a list of it if it is not a list already.  Then the first form is inserted as the last item in the second form, making a list of that form if necessary.  This process continues for all the forms.  Using ->> can sometimes make your code more readable.
#+begin_src clojure
(def __ )
(= (__ (map inc (take 3 (drop 2 [2 5 4 1 3 6]))))
   (->> [2 5 4 1 3 6] (drop 2) (take 3) (map inc) (__))
   11)
#+end_src
* 73. Analyze a Tic-Tac-Toe Board
A [tic-tac-toe]("http://en.wikipedia.org/wiki/Tic-tac-toe") board is represented by a two dimensional vector. X is represented by :x, O is represented by :o, and empty is represented by :e.  A player wins by placing three Xs or three Os in a horizontal, vertical, or diagonal row.  Write a function which analyzes a tic-tac-toe board and returns :x if X has won, :o if O has won, and nil if neither player has won.
#+begin_src clojure
(def __ )
(= nil (__ [[:e :e :e]
            [:e :e :e]
            [:e :e :e]]))
(= :x (__ [[:x :e :o]
           [:x :e :e]
           [:x :e :o]]))
(= :o (__ [[:e :x :e]
           [:o :o :o]
           [:x :e :x]]))
(= nil (__ [[:x :e :o]
            [:x :x :e]
            [:o :x :o]]))
(= :x (__ [[:x :e :e]
           [:o :x :e]
           [:o :e :x]]))
(= :o (__ [[:x :e :o]
           [:x :o :e]
           [:o :e :x]]))
(= nil (__ [[:x :o :x]
            [:x :o :x]
            [:o :x :o]]))
#+end_src
* 74. Filter Perfect Squares
Given a string of comma separated integers, write a function which returns a new comma separated string that only contains the numbers which are perfect squares.
#+begin_src clojure
(def __ )
(= (__ "4,5,6,7,8,9") "4,9")
(= (__ "15,16,25,36,37") "16,25,36")
#+end_src
* 75. Euler's Totient Function
Two numbers are coprime if their greatest common divisor equals 1.  Euler's totient function f(x) is defined as the number of positive integers less than x which are coprime to x.  The special case f(1) equals 1.  Write a function which calculates Euler's totient function.
#+begin_src clojure
(def __ )
(= (__ 1) 1)
(= (__ 10) (count '(1 3 7 9)) 4)
(= (__ 40) 16)
(= (__ 99) 60)
#+end_src
* 76. Intro to Trampoline
The trampoline function takes a function f and a variable number of parameters.  Trampoline calls f with any parameters that were supplied.  If f returns a function, trampoline calls that function with no arguments.  This is repeated, until the return value is not a function, and then trampoline returns that non-function value.  This is useful for implementing mutually recursive algorithms in a way that won't consume the stack.
#+begin_src clojure
(def __ )
(= __
   (letfn
     [(foo [x y] #(bar (conj x y) y))
      (bar [x y] (if (> (last x) 10)
                   x
                   #(foo x (+ 2 y))))]
     (trampoline foo [] 1)))
#+end_src
* 77. Anagram Finder
Write a function which finds all the anagrams in a vector of words.  A word x is an anagram of word y if all the letters in x can be rearranged in a different order to form y.  Your function should return a set of sets, where each sub-set is a group of words which are anagrams of each other.  Each sub-set should have at least two words.  Words without any anagrams should not be included in the result.
#+begin_src clojure
(def __ )
(= (__ ["meat" "mat" "team" "mate" "eat"])
   #{#{"meat" "team" "mate"}})
(= (__ ["veer" "lake" "item" "kale" "mite" "ever"])
   #{#{"veer" "ever"} #{"lake" "kale"} #{"mite" "item"}})
#+end_src
* 78. Reimplement Trampoline
Reimplement the function described in [ "Intro to Trampoline"]("76").
#+begin_src clojure
(def __ )
(= (letfn [(triple [x] #(sub-two (* 3 x)))
          (sub-two [x] #(stop?(- x 2)))
          (stop? [x] (if (> x 50) x #(triple x)))]
    (__ triple 2))
  82)
(= (letfn [(my-even? [x] (if (zero? x) true #(my-odd? (dec x))))
          (my-odd? [x] (if (zero? x) false #(my-even? (dec x))))]
    (map (partial __ my-even?) (range 6)))
  [true false true false true false])
#+end_src
* 79. Triangle Minimal Path
Write a function which calculates the sum of the minimal path through a triangle.  The triangle is represented as a collection of vectors.  The path should start at the top of the triangle and move to an adjacent number on the next row until the bottom of the triangle is reached.
#+begin_src clojure
(def __ )
(= 7 (__ '([1]
          [2 4]
         [5 1 4]
        [2 3 4 5]))) ; 1->2->1->3
(= 20 (__ '([3]
           [2 4]
          [1 9 3]
         [9 9 2 4]
        [4 6 6 7 8]
       [5 7 3 5 1 4]))) ; 3->4->3->2->7->1
#+end_src
* 80. Perfect Numbers
A number is "perfect" if the sum of its divisors equal the number itself.  6 is a perfect number because 1+2+3=6.  Write a function which returns true for perfect numbers and false otherwise.
#+begin_src clojure
(def __ )
(= (__ 6) true)
(= (__ 7) false)
(= (__ 496) true)
(= (__ 500) false)
(= (__ 8128) true)
#+end_src
* 81. Set Intersection
Write a function which returns the intersection of two sets.  The intersection is the sub-set of items that each set has in common.
#+begin_src clojure
(def __ )
(= (__ #{0 1 2 3} #{2 3 4 5}) #{2 3})
(= (__ #{0 1 2} #{3 4 5}) #{})
(= (__ #{:a :b :c :d} #{:c :e :a :f :d}) #{:a :c :d})
#+end_src
* 82. Word Chains
A word chain consists of a set of words ordered so that each word differs by only one letter from the words directly before and after it.  The one letter difference can be either an insertion, a deletion, or a substitution.  Here is an example word chain:  
<br/>

cat -> cot -> coat -> oat -> hat -> hot -> hog -> dog  
<br/>

Write a function which takes a sequence of words, and returns true if they can be arranged into one continous word chain, and false if they cannot.
#+begin_src clojure
(def __ )
(= true (__ #{"hat" "coat" "dog" "cat" "oat" "cot" "hot" "hog"}))
(= false (__ #{"cot" "hot" "bat" "fat"}))
(= false (__ #{"to" "top" "stop" "tops" "toss"}))
(= true (__ #{"spout" "do" "pot" "pout" "spot" "dot"}))
(= true (__ #{"share" "hares" "shares" "hare" "are"}))
(= false (__ #{"share" "hares" "hare" "are"}))
#+end_src
* 83. A Half-Truth
Write a function which takes a variable number of booleans.  Your function should return true if some of the parameters are true, but not all of the parameters are true.  Otherwise your function should return false.
#+begin_src clojure
(def __ )
(= false (__ false false))
(= true (__ true false))
(= false (__ true))
(= true (__ false true false))
(= false (__ true true true))
(= true (__ true true true false))
#+end_src
* 84. Transitive Closure
Write a function which generates the [transitive closure]("http://en.wikipedia.org/wiki/Transitive_closure") of a [binary relation]("http://en.wikipedia.org/wiki/Binary_relation").  The relation will be represented as a set of 2 item vectors.
#+begin_src clojure
(def __ )
(let [divides #{[8 4] [9 3] [4 2] [27 9]}]
  (= (__ divides) #{[4 2] [8 4] [8 2] [9 3] [27 9] [27 3]}))
(let [more-legs
      #{["cat" "man"] ["man" "snake"] ["spider" "cat"]}]
  (= (__ more-legs)
     #{["cat" "man"] ["cat" "snake"] ["man" "snake"]
       ["spider" "cat"] ["spider" "man"] ["spider" "snake"]}))
(let [progeny
      #{["father" "son"] ["uncle" "cousin"] ["son" "grandson"]}]
  (= (__ progeny)
     #{["father" "son"] ["father" "grandson"]
       ["uncle" "cousin"] ["son" "grandson"]}))
#+end_src
* 85. Power Set
Write a function which generates the [power set]("http://en.wikipedia.org/wiki/Power_set") of a given set.  The power set of a set x is the set of all subsets of x, including the empty set and x itself.
#+begin_src clojure
(def __ )
(= (__ #{1 :a}) #{#{1 :a} #{:a} #{} #{1}})
(= (__ #{}) #{#{}})
(= (__ #{1 2 3})
   #{#{} #{1} #{2} #{3} #{1 2} #{1 3} #{2 3} #{1 2 3}})
(= (count (__ (into #{} (range 10)))) 1024)
#+end_src
* 86. Happy numbers
Happy numbers are positive integers that follow a particular formula: take each individual digit, square it, and then sum the squares to get a new number. Repeat with the new number and eventually, you might get to a number whose squared sum is 1. This is a happy number. An unhappy number (or sad number) is one that loops endlessly. Write a function that determines if a number is happy or not.
#+begin_src clojure
(def __ )
(= (__ 7) true)
(= (__ 986543210) true)
(= (__ 2) false)
(= (__ 3) false)
#+end_src
* 88. Symmetric Difference
Write a function which returns the symmetric difference of two sets.  The symmetric difference is the set of items belonging to one but not both of the two sets.
#+begin_src clojure
(def __ )
(= (__ #{1 2 3 4 5 6} #{1 3 5 7}) #{2 4 6 7})
(= (__ #{:a :b :c} #{}) #{:a :b :c})
(= (__ #{} #{4 5 6}) #{4 5 6})
(= (__ #{[1 2] [2 3]} #{[2 3] [3 4]}) #{[1 2] [3 4]})
#+end_src
* 89. Graph Tour
Starting with a graph you must write a function that returns true if it is possible to make a tour of the graph in which every edge is visited exactly once.  
<br/>

The graph is represented by a vector of tuples, where each tuple represents a single edge.  
<br/>

The rules are:  
<br/>
- You can start at any node.  
- You must visit each edge exactly once.- All edges are undirected.
#+begin_src clojure
(def __ )
(= true (__ [[:a :b]]))
(= false (__ [[:a :a] [:b :b]]))
(= false (__ [[:a :b] [:a :b] [:a :c] [:c :a]
               [:a :d] [:b :d] [:c :d]]))
(= true (__ [[1 2] [2 3] [3 4] [4 1]]))
(= true (__ [[:a :b] [:a :c] [:c :b] [:a :e]
              [:b :e] [:a :d] [:b :d] [:c :e]
              [:d :e] [:c :f] [:d :f]]))
(= false (__ [[1 2] [2 3] [2 4] [2 5]]))
#+end_src
* 90. Cartesian Product
Write a function which calculates the [ Cartesian product]("http://en.wikipedia.org/wiki/Cartesian_product") of two sets.
#+begin_src clojure
(def __ )
(= (__ #{"ace" "king" "queen"} #{"&#9824;" "&#9829;" "&#9830;" "&#9827;"})
   #{["ace"   "&#9824;"] ["ace"   "&#9829;"] ["ace"   "&#9830;"] ["ace"   "&#9827;"]
     ["king"  "&#9824;"] ["king"  "&#9829;"] ["king"  "&#9830;"] ["king"  "&#9827;"]
     ["queen" "&#9824;"] ["queen" "&#9829;"] ["queen" "&#9830;"] ["queen" "&#9827;"]})
(= (__ #{1 2 3} #{4 5})
   #{[1 4] [2 4] [3 4] [1 5] [2 5] [3 5]})
(= 300 (count (__ (into #{} (range 10))
                  (into #{} (range 30)))))
#+end_src
* 91. Graph Connectivity
Given a graph, determine whether the graph is connected. A connected graph is such that a path exists between any two given nodes.  
<br/>

-Your function must return true if the graph is connected and false otherwise.  
<br/>

-You will be given a set of tuples representing the edges of a graph. Each member of a tuple being a vertex/node in the graph.  
<br/>

-Each edge is undirected (can be traversed either direction). 
#+begin_src clojure
(def __ )
(= true (__ #{[:a :a]}))
(= true (__ #{[:a :b]}))
(= false (__ #{[1 2] [2 3] [3 1]
               [4 5] [5 6] [6 4]}))
(= true (__ #{[1 2] [2 3] [3 1]
              [4 5] [5 6] [6 4] [3 4]}))
(= false (__ #{[:a :b] [:b :c] [:c :d]
               [:x :y] [:d :a] [:b :e]}))
(= true (__ #{[:a :b] [:b :c] [:c :d]
              [:x :y] [:d :a] [:b :e] [:x :a]}))
#+end_src
* 92. Read Roman numerals
Roman numerals are easy to recognize, but not everyone knows all the rules necessary to work with them. Write a function to parse a Roman-numeral string and return the number it represents.   
<br />

 You can assume that the input will be well-formed, in upper-case, and follow the [subtractive principle]("http://en.wikipedia.org/wiki/Roman_numerals#Subtractive_principle"). You don't need to handle any numbers greater than MMMCMXCIX (3999), the largest number representable with ordinary letters.
#+begin_src clojure
(def __ )
(= 14 (__ "XIV"))
(= 827 (__ "DCCCXXVII"))
(= 3999 (__ "MMMCMXCIX"))
(= 48 (__ "XLVIII"))

#+end_src
* 93. Partially Flatten a Sequence
Write a function which flattens any nested combination of sequential things (lists, vectors, etc.), but maintains the lowest level sequential items.  The result should be a sequence of sequences with only one level of nesting.
#+begin_src clojure
(def __ )
(= (__ [["Do"] ["Nothing"]])
   [["Do"] ["Nothing"]])
(= (__ [[[[:a :b]]] [[:c :d]] [:e :f]])
   [[:a :b] [:c :d] [:e :f]])
(= (__ '((1 2)((3 4)((((5 6)))))))
   '((1 2)(3 4)(5 6)))
#+end_src
* 94. Game of Life
The [game of life]("http://en.wikipedia.org/wiki/Conway's_Game_of_Life") is a cellular automaton devised by mathematician John Conway.   
<br/>

The 'board' consists of both live (#) and dead ( ) cells. Each cell interacts with its eight neighbours (horizontal, vertical, diagonal), and its next state is dependent on the following rules:  
<br/>

1) Any live cell with fewer than two live neighbours dies, as if caused by under-population.  
2) Any live cell with two or three live neighbours lives on to the next generation.  
3) Any live cell with more than three live neighbours dies, as if by overcrowding.  
4) Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.  
<br/>

Write a function that accepts a board, and returns a board representing the next generation of cells.
#+begin_src clojure
(def __ )
(= (__ ["      "  
        " ##   "
        " ##   "
        "   ## "
        "   ## "
        "      "])
   ["      "  
    " ##   "
    " #    "
    "    # "
    "   ## "
    "      "])
(= (__ ["     "
        "     "
        " ### "
        "     "
        "     "])
   ["     "
    "  #  "
    "  #  "
    "  #  "
    "     "])
(= (__ ["      "
        "      "
        "  ### "
        " ###  "
        "      "
        "      "])
   ["      "
    "   #  "
    " #  # "
    " #  # "
    "  #   "
    "      "])
#+end_src
* 95. To Tree, or not to Tree
Write a predicate which checks whether or not a given sequence represents a [binary tree]("http://en.wikipedia.org/wiki/Binary_tree").  Each node in the tree must have a value, a left child, and a right child.
#+begin_src clojure
(def __ )
(= (__ '(:a (:b nil nil) nil))
   true)
(= (__ '(:a (:b nil nil)))
   false)
(= (__ [1 nil [2 [3 nil nil] [4 nil nil]]])
   true)
(= (__ [1 [2 nil nil] [3 nil nil] [4 nil nil]])
   false)
(= (__ [1 [2 [3 [4 nil nil] nil] nil] nil])
   true)
(= (__ [1 [2 [3 [4 false nil] nil] nil] nil])
   false)
(= (__ '(:a nil ()))
   false)

#+end_src
* 96. Beauty is Symmetry
Let us define a binary tree as "symmetric" if the left half of the tree is the mirror image of the right half of the tree.  Write a predicate to determine whether or not a given binary tree is symmetric. (see [To Tree, or not to Tree]('/problem/95') for a reminder on the tree representation we're using).
#+begin_src clojure
(def __ )
(= (__ '(:a (:b nil nil) (:b nil nil))) true)
(= (__ '(:a (:b nil nil) nil)) false)
(= (__ '(:a (:b nil nil) (:c nil nil))) false)
(= (__ [1 [2 nil [3 [4 [5 nil nil] [6 nil nil]] nil]]
          [2 [3 nil [4 [6 nil nil] [5 nil nil]]] nil]])
   true)
(= (__ [1 [2 nil [3 [4 [5 nil nil] [6 nil nil]] nil]]
          [2 [3 nil [4 [5 nil nil] [6 nil nil]]] nil]])
   false)
(= (__ [1 [2 nil [3 [4 [5 nil nil] [6 nil nil]] nil]]
          [2 [3 nil [4 [6 nil nil] nil]] nil]])
   false)
#+end_src
* 97. Pascal's Triangle
[Pascal's triangle]("http://en.wikipedia.org/wiki/Pascal%27s_triangle") is a triangle of numbers computed using the following rules:  
- The first row is 1.- Each successive row is computed by adding together adjacent numbers in the row above, and adding a 1 to the beginning and end of the row.  
<br/>

Write a function which returns the nth row of Pascal's Triangle.   
#+begin_src clojure
(def __ )
(= (__ 1) [1])
(= (map __ (range 1 6))
   [     [1]
        [1 1]
       [1 2 1]
      [1 3 3 1]
     [1 4 6 4 1]])
(= (__ 11)
   [1 10 45 120 210 252 210 120 45 10 1])
#+end_src
* 98. Equivalence Classes
A function f defined on a domain D induces an [equivalence relation]("http://en.wikipedia.org/wiki/Equivalence_relation") on D, as follows: a is equivalent to b with respect to f if and only if (f a) is equal to (f b).  Write a function with arguments f and D that computes the [equivalence classes]("http://en.wikipedia.org/wiki/Equivalence_class") of D with respect to f.
#+begin_src clojure
(def __ )
(= (__ #(* % %) #{-2 -1 0 1 2})
   #{#{0} #{1 -1} #{2 -2}})
(= (__ #(rem % 3) #{0 1 2 3 4 5 })
   #{#{0 3} #{1 4} #{2 5}})
(= (__ identity #{0 1 2 3 4})
   #{#{0} #{1} #{2} #{3} #{4}})
(= (__ (constantly true) #{0 1 2 3 4})
   #{#{0 1 2 3 4}})

#+end_src
* 99. Product Digits
Write a function which multiplies two numbers and returns the result as a sequence of its digits.
#+begin_src clojure
(def __ )
(= (__ 1 1) [1])
(= (__ 99 9) [8 9 1])
(= (__ 999 99) [9 8 9 0 1])
#+end_src
* 100. Least Common Multiple
Write a function which calculates the [least common multiple]("http://en.wikipedia.org/wiki/Least_common_multiple").  Your function should accept a variable number of positive integers or ratios. 
#+begin_src clojure
(def __ )
(== (__ 2 3) 6)
(== (__ 5 3 7) 105)
(== (__ 1/3 2/5) 2)
(== (__ 3/4 1/6) 3/2)
(== (__ 7 5/7 2 3/5) 210)
#+end_src
* 101. Levenshtein Distance
Given two sequences x and y, calculate the [Levenshtein distance]("https://secure.wikimedia.org/wikipedia/en/wiki/Levenshtein_distance") of x and y, i. e. the minimum number of edits needed to transform x into y.  The allowed edits are:  
<br/>
- insert a single item  
- delete a single item  
- replace a single item with another item  
<br/>

WARNING: Some of the test cases may timeout if you write an inefficient solution!
#+begin_src clojure
(def __ )
(= (__ "kitten" "sitting") 3)
(= (__ "closure" "clojure") (__ "clojure" "closure") 1)
(= (__ "xyx" "xyyyx") 2)
(= (__ "" "123456") 6)
(= (__ "Clojure" "Clojure") (__ "" "") (__ [] []) 0)
(= (__ [1 2 3 4] [0 2 3 4 5]) 2)
(= (__ '(:a :b :c :d) '(:a :d)) 2)
(= (__ "ttttattttctg" "tcaaccctaccat") 10)
(= (__ "gaattctaatctc" "caaacaaaaaattt") 9)
#+end_src
* 102. intoCamelCase
When working with java, you often need to create an object with `fieldsLikeThis`, but you would rather work with a hashmap that has `:keys-like-this` until it's time to convert. Write a function which takes lower-case hyphen-separated strings and converts them to camel-case strings.
#+begin_src clojure
(def __ )
(= (__ "something") "something")
(= (__ "multi-word-key") "multiWordKey")
(= (__ "leaveMeAlone") "leaveMeAlone")
#+end_src
* 103. Generating k-combinations
Given a sequence S consisting of n elements generate all [k-combinations]("https://secure.wikimedia.org/wikipedia/en/wiki/Combination") of S, i. e. generate all possible sets consisting of k distinct elements taken from S.  The number of k-combinations for a sequence is equal to the [binomial coefficient]("https://secure.wikimedia.org/wikipedia/en/wiki/Binomial_coefficient").
#+begin_src clojure
(def __ )
(= (__ 1 #{4 5 6}) #{#{4} #{5} #{6}})
(= (__ 10 #{4 5 6}) #{})
(= (__ 2 #{0 1 2}) #{#{0 1} #{0 2} #{1 2}})
(= (__ 3 #{0 1 2 3 4}) #{#{0 1 2} #{0 1 3} #{0 1 4} #{0 2 3} #{0 2 4}
                         #{0 3 4} #{1 2 3} #{1 2 4} #{1 3 4} #{2 3 4}})
(= (__ 4 #{[1 2 3] :a "abc" "efg"}) #{#{[1 2 3] :a "abc" "efg"}})
(= (__ 2 #{[1 2 3] :a "abc" "efg"}) #{#{[1 2 3] :a} #{[1 2 3] "abc"} #{[1 2 3] "efg"}
                                    #{:a "abc"} #{:a "efg"} #{"abc" "efg"}})
#+end_src
* 104. Write Roman Numerals
This is the inverse of [Problem 92]('92'), but much easier. Given an integer smaller than 4000, return the corresponding roman numeral in uppercase, adhering to the [subtractive principle]('http://www.numericana.com/answer/roman.htm#valid').
#+begin_src clojure
(def __ )
(= "I" (__ 1))
(= "XXX" (__ 30))
(= "IV" (__ 4))
(= "CXL" (__ 140))
(= "DCCCXXVII" (__ 827))
(= "MMMCMXCIX" (__ 3999))
(= "XLVIII" (__ 48))
#+end_src
* 105. Identify keys and values
Given an input sequence of keywords and numbers, create a map such that each key in the map is a keyword, and the value is a sequence of all the numbers (if any) between it and the next keyword in the sequence.
#+begin_src clojure
(def __ )
(= {} (__ []))
(= {:a [1]} (__ [:a 1]))
(= {:a [1], :b [2]} (__ [:a 1, :b 2]))
(= {:a [1 2 3], :b [], :c [4]} (__ [:a 1 2 3 :b :c 4]))
#+end_src
* 106. Number Maze
Given a pair of numbers, the start and end point, find a path between the two using only three possible operations:


 
- double 
- halve (odd numbers cannot be halved) 
- add 2

  Find the shortest path through the "maze". Because there are multiple shortest paths, you must return the length of the shortest path, not the path itself.
#+begin_src clojure
(def __ )
(= 1 (__ 1 1))  ; 1
(= 3 (__ 3 12)) ; 3 6 12
(= 3 (__ 12 3)) ; 12 6 3
(= 3 (__ 5 9))  ; 5 7 9
(= 9 (__ 9 2))  ; 9 18 20 10 12 6 8 4 2
(= 5 (__ 9 12)) ; 9 11 22 24 12

#+end_src
* 107. Simple closures
Lexical scope and first-class functions are two of the most basic building blocks of a functional language like Clojure. When you combine the two together, you get something very powerful called **lexical closures**. With these, you can exercise a great deal of control over the lifetime of your local bindings, saving their values for use later, long after the code you're running now has finished.  It can be hard to follow in the abstract, so let us build a simple closure. Given a positive integer _n_, return a function `(f x)` which computes _x<sup>n</sup>_. Observe that the effect of this is to preserve the value of _n_ for use outside the scope in which it is defined.
#+begin_src clojure
(def __ )
(= 256 ((__ 2) 16),
       ((__ 8) 2))
(= [1 8 27 64] (map (__ 3) [1 2 3 4]))
(= [1 2 4 8 16] (map #((__ %) 2) [0 1 2 3 4]))
#+end_src
* 122. Read a binary number
Convert a binary number, provided in the form of a string, to its numerical value.
#+begin_src clojure
(def __ )
(= 0     (__ "0"))
(= 7     (__ "111"))
(= 8     (__ "1000"))
(= 9     (__ "1001"))
(= 255   (__ "11111111"))
(= 1365  (__ "10101010101"))
(= 65535 (__ "1111111111111111"))
#+end_src
* 108. Lazy Searching
Given any number of sequences, each sorted from smallest to largest, find the smallest single number which appears in all of the sequences. The sequences may be infinite, so be careful to search lazily.
#+begin_src clojure
(def __ )
(= 3 (__ [3 4 5]))
(= 4 (__ [1 2 3 4 5 6 7] [0.5 3/2 4 19]))
(= 7 (__ (range) (range 0 100 7/6) [2 3 5 7 11 13]))
(= 64 (__ (map #(* % % %) (range)) ;; perfect cubes
          (filter #(zero? (bit-and % (dec %))) (range)) ;; powers of 2
          (iterate inc 20))) ;; at least as large as 20
#+end_src
* 110. Sequence of pronunciations
Write a function that returns a lazy sequence of "pronunciations" of a sequence of numbers. A pronunciation of each element in the sequence consists of the number of repeating identical numbers and the number itself. For example, `[1 1]` is pronounced as `[2 1]` ("two ones"), which in turn is pronounced as `[1 2 1 1]` ("one two, one one").Your function should accept an initial sequence of numbers, and return an infinite lazy sequence of pronunciations, each element being a pronunciation of the previous element.
#+begin_src clojure
(def __ )
(= [[1 1] [2 1] [1 2 1 1]] (take 3 (__ [1])))
(= [3 1 2 4] (first (__ [1 1 1 4 4])))
(= [1 1 1 3 2 1 3 2 1 1] (nth (__ [1]) 6))
(= 338 (count (nth (__ [3 2]) 15)))

#+end_src
* 111. Crossword puzzle
Write a function that takes a string and a partially-filled crossword puzzle board, and determines if the input string can be legally placed onto the board.   The crossword puzzle board consists of a collection of partially-filled rows.  Empty spaces are denoted with an underscore (_), unusable spaces are denoted with a hash symbol (#), and pre-filled spaces have a character in place; the whitespace characters are for legibility and should be ignored.  For a word to be legally placed on the board:  - It may use empty spaces (underscores)  - It may use but must not conflict with any pre-filled characters.  - It must not use any unusable spaces (hashes).  - There must be no empty spaces (underscores) or extra characters before or after the word (the word may be bound by unusable spaces though).  - Characters are not case-sensitive.   - Words may be placed vertically (proceeding top-down only), or horizontally (proceeding left-right only).
#+begin_src clojure
(def __ )
(= true  (__ "the" ["_ # _ _ e"]))
(= false (__ "the" ["c _ _ _"
                    "d _ # e"
                    "r y _ _"]))
(= true  (__ "joy" ["c _ _ _"
                    "d _ # e"
                    "r y _ _"]))
(= false (__ "joy" ["c o n j"
                    "_ _ y _"
                    "r _ _ #"]))
(= true  (__ "clojure" ["_ _ _ # j o y"
                        "_ _ o _ _ _ _"
                        "_ _ f _ # _ _"]))

#+end_src
* 112. Sequs Horribilis
Create a function which takes an integer and a nested collection of integers as arguments.  Analyze the elements of the input collection and return a sequence which maintains the nested structure, and which includes all elements starting from the head whose sum is less than or equal to the input integer.
#+begin_src clojure
(def __ )
(=  (__ 10 [1 2 [3 [4 5] 6] 7])
   '(1 2 (3 (4))))
(=  (__ 30 [1 2 [3 [4 [5 [6 [7 8]] 9]] 10] 11])
   '(1 2 (3 (4 (5 (6 (7)))))))
(=  (__ 9 (range))
   '(0 1 2 3))
(=  (__ 1 [[[[[1]]]]])
   '(((((1))))))
(=  (__ 0 [1 2 [3 [4 5] 6] 7])
   '())
(=  (__ 0 [0 0 [0 [0]]])
   '(0 0 (0 (0))))
(=  (__ 1 [-10 [1 [2 3 [4 5 [6 7 [8]]]]]])
   '(-10 (1 (2 3 (4)))))
#+end_src
* 113. Making Data Dance
Write a function that takes a variable number of integer arguments.  If the output is coerced into a string, it should return a comma (and space) separated list of the inputs sorted smallest to largest.  If the output is coerced into a sequence, it should return a seq of unique input elements in the same order as they were entered.
#+begin_src clojure
(def __ )
(= "1, 2, 3" (str (__ 2 1 3)))
(= '(2 1 3) (seq (__ 2 1 3)))
(= '(2 1 3) (seq (__ 2 1 3 3 1 2)))
(= '(1) (seq (apply __ (repeat 5 1))))
(= "1, 1, 1, 1, 1" (str (apply __ (repeat 5 1))))
(and (= nil (seq (__)))
     (=  "" (str (__))))
#+end_src
* 114. Global take-while
[take-while]() is great for filtering sequences, but it limited: you can only examine a single item of the sequence at a time. What if you need to keep track of some state as you go over the sequence?  Write a function which accepts an integer `n`, a predicate `p`, and a sequence. It should return a lazy sequence of items in the list up to, but not including, the `n`th item that satisfies the predicate.
#+begin_src clojure
(def __ )
(= [2 3 5 7 11 13]
   (__ 4 #(= 2 (mod % 3))
         [2 3 5 7 11 13 17 19 23]))
(= ["this" "is" "a" "sentence"]
   (__ 3 #(some #{\i} %)
         ["this" "is" "a" "sentence" "i" "wrote"]))
(= ["this" "is"]
   (__ 1 #{"a"}
         ["this" "is" "a" "sentence" "i" "wrote"]))
#+end_src
* 115. The Balance of N
A balanced number is one whose component digits have the same sum on the left and right halves of the number.  Write a function which accepts an integer n, and returns true iff n is balanced.
#+begin_src clojure
(def __ )
(= true (__ 11))
(= true (__ 121))
(= false (__ 123))
(= true (__ 0))
(= false (__ 88099))
(= true (__ 89098))
(= true (__ 89089))
(= (take 20 (filter __ (range)))
   [0 1 2 3 4 5 6 7 8 9 11 22 33 44 55 66 77 88 99 101])  
#+end_src
* 116. Prime Sandwich
A [balanced prime]("http://en.wikipedia.org/wiki/Balanced_prime") is a prime number which is also the mean of the primes directly before and after it in the sequence of valid primes.  Create a function which takes an integer n, and returns true iff it is a balanced prime.
#+begin_src clojure
(def __ )
(= false (__ 4))
(= true (__ 563))
(= 1103 (nth (filter __ (range)) 15))
#+end_src
* 117. For Science!
A mad scientist with tenure has created an experiment tracking mice in a maze.  Several mazes have been randomly generated, and you've been tasked with writing a program to determine the mazes in which it's possible for the mouse to reach the cheesy endpoint.  Write a function which accepts a maze in the form of a collection of rows, each row is a string where: 


 
- spaces represent areas where the mouse can walk freely 
- hashes (#) represent walls where the mouse can not walk 
- M represents the mouse's starting point 
- C represents the cheese which the mouse must reach 

 The mouse is not allowed to travel diagonally in the maze (only up/down/left/right), nor can he escape the edge of the maze.  Your function must return true iff the maze is solvable by the mouse.
#+begin_src clojure
(def __ )
(= true  (__ ["M   C"]))
(= false (__ ["M # C"]))
(= true  (__ ["#######"
              "#     #"
              "#  #  #"
              "#M # C#"
              "#######"]))
(= false (__ ["########"
              "#M  #  #"
              "#   #  #"
              "# # #  #"
              "#   #  #"
              "#  #   #"
              "#  # # #"
              "#  #   #"
              "#  #  C#"
              "########"]))
(= false (__ ["M     "
              "      "
              "      "
              "      "
              "    ##"
              "    #C"]))
(= true  (__ ["C######"
              " #     "
              " #   # "
              " #   #M"
              "     # "]))
(= true  (__ ["C# # # #"
              "        "
              "# # # # "
              "        "
              " # # # #"
              "        "
              "# # # #M"]))
#+end_src
* 118. Re-implement Map
Map is one of the core elements of a functional programming language. Given a function `f` and an input sequence `s`, return a lazy sequence of `(f x)` for each element `x` in `s`.
#+begin_src clojure
(def __ )
(= [3 4 5 6 7]
   (__ inc [2 3 4 5 6]))
(= (repeat 10 nil)
   (__ (fn [_] nil) (range 10)))
(= [1000000 1000001]
   (->> (__ inc (range))
        (drop (dec 1000000))
        (take 2)))
#+end_src
* 119. Win at Tic-Tac-Toe
As in [Problem 73]("/problem/73"), a tic-tac-toe board is represented by a two dimensional vector. X is represented by :x, O is represented by :o, and empty is represented by :e. Create a function that accepts a game piece and board as arguments, and returns a set (possibly empty) of all valid board placements of the game piece which would result in an immediate win.  Board coordinates should be as in calls to `get-in`. For example, `[0 1]` is the topmost row, center position.
#+begin_src clojure
(def __ )
(= (__ :x [[:o :e :e] 
           [:o :x :o] 
           [:x :x :e]])
   #{[2 2] [0 1] [0 2]})
(= (__ :x [[:x :o :o] 
           [:x :x :e] 
           [:e :o :e]])
   #{[2 2] [1 2] [2 0]})
(= (__ :x [[:x :e :x] 
           [:o :x :o] 
           [:e :o :e]])
   #{[2 2] [0 1] [2 0]})
(= (__ :x [[:x :x :o] 
           [:e :e :e] 
           [:e :e :e]])
   #{})
(= (__ :o [[:x :x :o] 
           [:o :e :o] 
           [:x :e :e]])
   #{[2 2] [1 1]})
#+end_src
* 120. Sum of square of digits
Write a function which takes a collection of integers as an argument.  Return the count of how many elements are smaller than the sum of their squared component digits.  For example: 10 is larger than 1 squared plus 0 squared; whereas 15 is smaller than 1 squared plus 5 squared.
#+begin_src clojure
(def __ )
(= 8 (__ (range 10)))
(= 19 (__ (range 30)))
(= 50 (__ (range 100)))
(= 50 (__ (range 1000)))
#+end_src
* 121. Universal Computation Engine
	 Given a mathematical formula in prefix notation, return a function that calculates the value of the formula. The formula can contain nested calculations using the four basic mathematical operators, numeric constants, and symbols representing variables. The returned function has to accept a single parameter containing the map of variable names to their values. 
#+begin_src clojure
(def __ )
(= 2 ((__ '(/ a b))
      '{b 8 a 16}))
(= 8 ((__ '(+ a b 2))
      '{a 2 b 4}))
(= [6 0 -4]
     (map (__ '(* (+ 2 a)
  	              (- 10 b)))
	        '[{a 1 b 8}
	          {b 5 a -2}
	          {a 2 b 11}]))
(= 1 ((__ '(/ (+ x 2)
              (* 3 (+ y 1))))
      '{x 4 y 1}))

#+end_src
* 124. Analyze Reversi
[Reversi]("http://en.wikipedia.org/wiki/Reversi") is normally played on an 8 by 8 board. In this problem, a 4 by 4 board is represented as a two-dimensional vector with black, white, and empty pieces represented by 'b, 'w, and 'e, respectively. Create a function that accepts a game board and color as arguments, and returns a map of legal moves for that color. Each key should be the coordinates of a legal move, and its value a set of the coordinates of the pieces flipped by that move.  Board coordinates should be as in calls to get-in. For example, `[0 1]` is the topmost row, second column from the left.
#+begin_src clojure
(def __ )
(= {[1 3] #{[1 2]}, [0 2] #{[1 2]}, [3 1] #{[2 1]}, [2 0] #{[2 1]}}
   (__ '[[e e e e]
         [e w b e]
         [e b w e]
         [e e e e]] 'w))
(= {[3 2] #{[2 2]}, [3 0] #{[2 1]}, [1 0] #{[1 1]}}
   (__ '[[e e e e]
         [e w b e]
         [w w w e]
         [e e e e]] 'b))
(= {[0 3] #{[1 2]}, [1 3] #{[1 2]}, [3 3] #{[2 2]}, [2 3] #{[2 2]}}
   (__ '[[e e e e]
         [e w b e]
         [w w b e]
         [e e b e]] 'w))
(= {[0 3] #{[2 1] [1 2]}, [1 3] #{[1 2]}, [2 3] #{[2 1] [2 2]}}
   (__ '[[e e w e]
         [b b w e]
         [b w w e]
         [b w w w]] 'b))

#+end_src
* 125. Gus' Quinundrum
Create a function of no arguments which returns a string that is an _exact_ copy of the function itself.   
<br />

 Hint: read [this]("http://en.wikipedia.org/wiki/Quine_(computing)") if you get stuck (this question is harder than it first appears); but it's worth the effort to solve it independently if you can!   
<br />

 Fun fact: Gus is the name of the [4Clojure dragon]("http://i.imgur.com/FBd8z.png").
#+begin_src clojure
(def __ )
(= (str '__) (__))
#+end_src
* 126. Through the Looking Class
Enter a value which satisfies the following:
#+begin_src clojure
(def __ )
(let [x __]
  (and (= (class x) x) x))
#+end_src
* 127. Love Triangle
Everyone loves triangles, and it's easy to understand why&mdash;they're so wonderfully symmetric (except scalenes, they suck).   
<br/>

 Your passion for triangles has led you to become a miner (and part-time Clojure programmer) where you work all day to chip out isosceles-shaped minerals from rocks gathered in a nearby open-pit mine.  There are too many rocks coming from the mine to harvest them all so you've been tasked with writing a program to analyze the mineral patterns of each rock, and determine which rocks have the biggest minerals.   
<br/>

 Someone has already written a [computer-vision]("http://en.wikipedia.org/wiki/Computer_vision") system for the mine.  It images each rock as it comes into the processing centre and creates a cross-sectional [bitmap]("http://en.wikipedia.org/wiki/Bit_array") of mineral (1) and rock (0) concentrations for each one.   
<br/>

 You must now create a function which accepts a collection of integers, each integer when read in base-2 gives the bit-representation of the rock (again, 1s are mineral and 0s are worthless scalene-like rock).  You must return the cross-sectional area of the largest harvestable mineral from the input rock, as follows:   
 


 
- The minerals only have smooth faces when sheared vertically or horizontally from the rock's cross-section 
- The mine is only concerned with harvesting isosceles triangles (such that one or two sides can be sheared) 
- If only one face of the mineral is sheared, its opposing vertex must be a point (ie. the smooth face must be of odd length), and its two equal-length sides must intersect the shear face at 45 (ie. those sides must cut even-diagonally) 
- The harvested mineral may not contain any traces of rock 
- The mineral may lie in any orientation in the plane 
- Area should be calculated as the sum of 1s that comprise the mineral 
- Minerals must have a minimum of three measures of area to be harvested 
- If no minerals can be harvested from the rock, your function should return nil 


#+begin_src clojure
(def __ )
(= 10 (__ [15 15 15 15 15]))
; 1111      1111
; 1111      *111
; 1111  ->  **11
; 1111      ***1
; 1111      ****
(= 15 (__ [1 3 7 15 31]))
; 00001      0000*
; 00011      000**
; 00111  ->  00***
; 01111      0****
; 11111      *****
(= 3 (__ [3 3]))
; 11      *1
; 11  ->  **
(= 4 (__ [7 3]))
; 111      ***
; 011  ->  0*1
(= 6 (__ [17 22 6 14 22]))
; 10001      10001
; 10110      101*0
; 00110  ->  00**0
; 01110      0***0
; 10110      10110
(= 9 (__ [18 7 14 14 6 3]))
; 10010      10010
; 00111      001*0
; 01110      01**0
; 01110  ->  0***0
; 00110      00**0
; 00011      000*1
(= nil (__ [21 10 21 10]))
; 10101      10101
; 01010      01010
; 10101  ->  10101
; 01010      01010
(= nil (__ [0 31 0 31 0]))
; 00000      00000
; 11111      11111
; 00000  ->  00000
; 11111      11111
; 00000      00000
#+end_src
* 128. Recognize Playing Cards
A standard American deck of playing cards has four suits - spades, hearts, diamonds, and clubs - and thirteen cards in each suit. Two is the lowest rank, followed by other integers up to ten; then the jack, queen, king, and ace.  It's convenient for humans to represent these cards as suit/rank pairs, such as H5 or DQ: the heart five and diamond queen respectively. But these forms are not convenient for programmers, so to write a card game you need some way to parse an input string into meaningful components. For purposes of determining rank, we will define the cards to be valued from 0 (the two) to 12 (the ace)  Write a function which converts (for example) the string "SJ" into a map of `{:suit :spade, :rank 9}`. A ten will always be represented with the single character "T", rather than the two characters "10".
#+begin_src clojure
(def __ )
(= {:suit :diamond :rank 10} (__ "DQ"))
(= {:suit :heart :rank 3} (__ "H5"))
(= {:suit :club :rank 12} (__ "CA"))
(= (range 13) (map (comp :rank __ str)
                   '[S2 S3 S4 S5 S6 S7
                     S8 S9 ST SJ SQ SK SA]))
#+end_src
* 130. Tree reparenting
Every node of a tree is connected to each of its children as well as its parent.  One can imagine grabbing one node of a tree and dragging it up to the root position, leaving all connections intact.  For example, below on the left is a binary tree.  By pulling the "c" node up to the root, we obtain the tree on the right.   
 !["http://i.imgur.com/UtD2T.png"]()   
 Note it is no longer binary as "c" had three connections total -- two children and one parent.  Each node is represented as a vector, which always has at least one element giving the name of the node as a symbol. Subsequent items in the vector represent the children of the node.  Because the children are ordered it's important that the tree you return keeps the children of each node in order and that the old parent node, if any, is appended on the right.  Your function will be given two args -- the name of the node that should become the new root, and the tree to transform. 
#+begin_src clojure
(def __ )
(= '(n)
   (__ 'n '(n)))
(= '(a (t (e)))
   (__ 'a '(t (e) (a))))
(= '(e (t (a)))
   (__ 'e '(a (t (e)))))
(= '(a (b (c)))
   (__ 'a '(c (b (a)))))
(= '(d 
      (b
        (c)
        (e)
        (a 
          (f 
            (g) 
            (h)))))
  (__ 'd '(a
            (b 
              (c) 
              (d) 
              (e))
            (f 
              (g)
              (h)))))
(= '(c 
      (d) 
      (e) 
      (b
        (f 
          (g) 
          (h))
        (a
          (i
          (j
            (k)
            (l))
          (m
            (n)
            (o))))))
   (__ 'c '(a
             (b
               (c
                 (d)
                 (e))
               (f
                 (g)
                 (h)))
             (i
               (j
                 (k)
                 (l))
               (m
                 (n)
                 (o))))))

#+end_src
* 131. Sum Some Set Subsets
Given a variable number of sets of integers, create a function which returns true iff all of the sets have a non-empty subset with an equivalent summation.
#+begin_src clojure
(def __ )
(= true  (__ #{-1 1 99} 
             #{-2 2 888}
             #{-3 3 7777})) ; ex. all sets have a subset which sums to zero
(= false (__ #{1}
             #{2}
             #{3}
             #{4}))
(= true  (__ #{1}))
(= false (__ #{1 -3 51 9} 
             #{0} 
             #{9 2 81 33}))
(= true  (__ #{1 3 5}
             #{9 11 4}
             #{-3 12 3}
             #{-3 4 -2 10}))
(= false (__ #{-1 -2 -3 -4 -5 -6}
             #{1 2 3 4 5 6 7 8 9}))
(= true  (__ #{1 3 5 7}
             #{2 4 6 8}))
(= true  (__ #{-1 3 -5 7 -9 11 -13 15}
             #{1 -3 5 -7 9 -11 13 -15}
             #{1 -1 2 -2 4 -4 8 -8}))
(= true  (__ #{-10 9 -8 7 -6 5 -4 3 -2 1}
             #{10 -9 8 -7 6 -5 4 -3 2 -1}))
#+end_src
* 132. Insert between two items
Write a function that takes a two-argument predicate, a value, and a collection; and returns a new collection where the `value` is inserted between every two items that satisfy the predicate.
#+begin_src clojure
(def __ )
(= '(1 :less 6 :less 7 4 3) (__ < :less [1 6 7 4 3]))
(= '(2) (__ > :more [2]))
(= [0 1 :x 2 :x 3 :x 4]  (__ #(and (pos? %) (< % %2)) :x (range 5)))
(empty? (__ > :more ()))
(= [0 1 :same 1 2 3 :same 5 8 13 :same 21]
   (take 12 (->> [0 1]
                 (iterate (fn [[a b]] [b (+ a b)]))
                 (map first) ; fibonacci numbers
                 (__ (fn [a b] ; both even or both odd
                       (= (mod a 2) (mod b 2)))
                     :same))))
#+end_src
* 134. A nil key
Write a function which, given a key and map, returns true [iff]("http://en.wikipedia.org/wiki/If_and_only_if") the map contains an entry with that key and its value is nil.
#+begin_src clojure
(def __ )
(true?  (__ :a {:a nil :b 2}))
(false? (__ :b {:a nil :b 2}))
(false? (__ :c {:a nil :b 2}))
#+end_src
* 135. Infix Calculator
Your friend Joe is always whining about Lisps using the prefix notation for math. Show him how you could easily write a function that does math using the infix notation. Is your favorite language that flexible, Joe?  Write a function that accepts a variable length mathematical expression consisting of numbers and the operations +, -, *, and /. Assume a simple calculator that does not do precedence and instead just calculates left to right.
#+begin_src clojure
(def __ )
(= 7  (__ 2 + 5))
(= 42 (__ 38 + 48 - 2 / 2))
(= 8  (__ 10 / 2 - 1 * 2))
(= 72 (__ 20 / 2 + 2 + 4 + 8 - 6 - 10 * 9))
#+end_src
* 137. Digits and bases
Write a function which returns a sequence of digits of a non-negative number (first argument) in numerical system with an arbitrary base (second argument). Digits should be represented with their integer values, e.g. 15 would be [1 5] in base 10, [1 1 1 1] in base 2 and [15] in base 16. 
#+begin_src clojure
(def __ )
(= [1 2 3 4 5 0 1] (__ 1234501 10))
(= [0] (__ 0 11))
(= [1 0 0 1] (__ 9 2))
(= [1 0] (let [n (rand-int 100000)](__ n n)))
(= [16 18 5 24 15 1] (__ Integer/MAX_VALUE 42))
#+end_src
* 138. Squares Squared
Create a function of two integer arguments: the start and end, respectively.  You must create a vector of strings which renders a 45 rotated square of integers which are successive squares from the start point up to and including the end point.  If a number comprises multiple digits, wrap them around the shape individually.  If there are not enough digits to complete the shape, fill in the rest with asterisk characters.  The direction of the drawing should be clockwise, starting from the center of the shape and working outwards, with the initial direction being down and to the right.
#+begin_src clojure
(def __ )
(= (__ 2 2) ["2"])
(= (__ 2 4) [" 2 "
             "* 4"
             " * "])
(= (__ 3 81) [" 3 "
              "1 9"
              " 8 "])
(= (__ 4 20) [" 4 "
              "* 1"
              " 6 "])
(= (__ 2 256) ["  6  "
               " 5 * "
               "2 2 *"
               " 6 4 "
               "  1  "])
(= (__ 10 10000) ["   0   "
                  "  1 0  "
                  " 0 1 0 "
                  "* 0 0 0"
                  " * 1 * "
                  "  * *  "
                  "   *   "])
#+end_src
* 140. Veitch, Please!
Create a function which accepts as input a boolean algebra function in the form of a set of sets, where the inner sets are collections of symbols corresponding to the input boolean variables which satisfy the function (the inputs of the inner sets are conjoint, and the sets themselves are disjoint... also known as canonical minterms).  Note:capitalized symbols represent truth, and lower-case symbols represent negation of the inputs.  Your function must return the minimal function which is logically equivalent to the input.  PS &mdash; You may want to give this a read before proceeding: [K-Maps]("http://en.wikipedia.org/wiki/K_map")
#+begin_src clojure
(def __ )
(= (__ #{#{'a 'B 'C 'd}
         #{'A 'b 'c 'd}
         #{'A 'b 'c 'D}
         #{'A 'b 'C 'd}
         #{'A 'b 'C 'D}
         #{'A 'B 'c 'd}
         #{'A 'B 'c 'D}
         #{'A 'B 'C 'd}})
   #{#{'A 'c} 
     #{'A 'b}
     #{'B 'C 'd}})
(= (__ #{#{'A 'B 'C 'D}
         #{'A 'B 'C 'd}})
   #{#{'A 'B 'C}})
(= (__ #{#{'a 'b 'c 'd}
         #{'a 'B 'c 'd}
         #{'a 'b 'c 'D}
         #{'a 'B 'c 'D}
         #{'A 'B 'C 'd}
         #{'A 'B 'C 'D}
         #{'A 'b 'C 'd}
         #{'A 'b 'C 'D}})
   #{#{'a 'c}
     #{'A 'C}})
(= (__ #{#{'a 'b 'c} 
         #{'a 'B 'c}
         #{'a 'b 'C}
         #{'a 'B 'C}})
   #{#{'a}})
(= (__ #{#{'a 'B 'c 'd}
         #{'A 'B 'c 'D}
         #{'A 'b 'C 'D}
         #{'a 'b 'c 'D}
         #{'a 'B 'C 'D}
         #{'A 'B 'C 'd}})
   #{#{'a 'B 'c 'd}
     #{'A 'B 'c 'D}
     #{'A 'b 'C 'D}
     #{'a 'b 'c 'D}
     #{'a 'B 'C 'D}
     #{'A 'B 'C 'd}})
(= (__ #{#{'a 'b 'c 'd}
         #{'a 'B 'c 'd}
         #{'A 'B 'c 'd}
         #{'a 'b 'c 'D}
         #{'a 'B 'c 'D}
         #{'A 'B 'c 'D}})
   #{#{'a 'c}
     #{'B 'c}})
(= (__ #{#{'a 'B 'c 'd}
         #{'A 'B 'c 'd}
         #{'a 'b 'c 'D}
         #{'a 'b 'C 'D}
         #{'A 'b 'c 'D}
         #{'A 'b 'C 'D}
         #{'a 'B 'C 'd}
         #{'A 'B 'C 'd}})
   #{#{'B 'd}
     #{'b 'D}})
(= (__ #{#{'a 'b 'c 'd}
         #{'A 'b 'c 'd}
         #{'a 'B 'c 'D}
         #{'A 'B 'c 'D}
         #{'a 'B 'C 'D}
         #{'A 'B 'C 'D}
         #{'a 'b 'C 'd}
         #{'A 'b 'C 'd}})
   #{#{'B 'D}
     #{'b 'd}})
#+end_src
* 141. Tricky card games
 In [trick-taking card games]("http://en.wikipedia.org/wiki/Trick-taking_game") such as bridge, spades, or hearts, cards are played in groups known as "tricks" - each player plays a single card, in order; the first player is said to "lead" to the trick. After all players have played, one card is said to have "won" the trick. How the winner is determined will vary by game, but generally the winner is the highest card played _in the suit that was led_. Sometimes (again varying by game), a particular suit will be designated "trump", meaning that its cards are more powerful than any others: if there is a trump suit, and any trumps are played, then the highest trump wins regardless of what was led.   Your goal is to devise a function that can determine which of a number of cards has won a trick. You should accept a trump suit, and return a function `winner`. Winner will be called on a sequence of cards, and should return the one which wins the trick. Cards will be represented in the format returned by [Problem 128, Recognize Playing Cards]("/problem/128/"): a hash-map of `:suit` and a numeric `:rank`. Cards with a larger rank are stronger. 
#+begin_src clojure
(def __ )
(let [notrump (__ nil)]
  (and (= {:suit :club :rank 9}  (notrump [{:suit :club :rank 4}
                                           {:suit :club :rank 9}]))
       (= {:suit :spade :rank 2} (notrump [{:suit :spade :rank 2}
                                           {:suit :club :rank 10}]))))
(= {:suit :club :rank 10} ((__ :club) [{:suit :spade :rank 2}
                                       {:suit :club :rank 10}]))
(= {:suit :heart :rank 8}
   ((__ :heart) [{:suit :heart :rank 6} {:suit :heart :rank 8}
                 {:suit :diamond :rank 10} {:suit :heart :rank 4}]))
#+end_src
* 143. dot product
Create a function that computes the [dot product]("http://en.wikipedia.org/wiki/Dot_product#Definition") of two sequences. You may assume that the vectors will have the same length.
#+begin_src clojure
(def __ )
(= 0 (__ [0 1 0] [1 0 0]))
(= 3 (__ [1 1 1] [1 1 1]))
(= 32 (__ [1 2 3] [4 5 6]))
(= 256 (__ [2 5 6] [100 10 1]))
#+end_src
* 144. Oscilrate
Write an oscillating iterate: a function that takes an initial value and a variable number of functions. It should return a lazy sequence of the functions applied to the value in order, restarting from the first function after it hits the end.
#+begin_src clojure
(def __ )
(= (take 3 (__ 3.14 int double)) [3.14 3 3.0])
(= (take 5 (__ 3 #(- % 3) #(+ 5 %))) [3 0 5 2 7])
(= (take 12 (__ 0 inc dec inc dec inc)) [0 1 0 1 0 1 2 1 2 1 2 3])

#+end_src
* 145. For the win
Clojure's [for]("http://clojuredocs.org/clojure_core/clojure.core/for") macro is a tremendously versatile mechanism for producing a sequence based on some other sequence(s). It can take some time to understand how to use it properly, but that investment will be paid back with clear, concise sequence-wrangling later. With that in mind, read over these `for` expressions and try to see how each of them produces the same result.
#+begin_src clojure
(def __ )
(= __ (for [x (range 40)
            :when (= 1 (rem x 4))]
        x))
(= __ (for [x (iterate #(+ 4 %) 0)
            :let [z (inc x)]
            :while (< z 40)]
        z))
(= __ (for [[x y] (partition 2 (range 20))]
        (+ x y)))
#+end_src
* 146. Trees into tables
Because Clojure's `for` macro allows you to "walk" over multiple sequences in a nested fashion, it is excellent for transforming all sorts of sequences. If you don't want a sequence as your final output (say you want a map), you are often still best-off using `for`, because you can produce a sequence and feed it into a map, for example.  For this problem, your goal is to "flatten" a map of hashmaps. Each key in your output map should be the "path"<sup>1</sup> that you would have to take in the original map to get to a value, so for example `{1 {2 3}}` should result in `{[1 2] 3}`. You only need to flatten one level of maps: if one of the values is a map, just leave it alone.  <sup>1</sup> That is, `(get-in original [k1 k2])` should be the same as `(get result [k1 k2])`
#+begin_src clojure
(def __ )
(= (__ '{a {p 1, q 2}
         b {m 3, n 4}})
   '{[a p] 1, [a q] 2
     [b m] 3, [b n] 4})
(= (__ '{[1] {a b c d}
         [2] {q r s t u v w x}})
   '{[[1] a] b, [[1] c] d,
     [[2] q] r, [[2] s] t,
     [[2] u] v, [[2] w] x})
(= (__ '{m {1 [a b c] 3 nil}})
   '{[m 1] [a b c], [m 3] nil})
#+end_src
* 147. Pascal's Trapezoid
Write a function that, for any given input vector of numbers, returns an infinite lazy sequence of vectors, where each next one is constructed from the previous following the rules used in [Pascal's Triangle]("http://en.wikipedia.org/wiki/Pascal's_triangle"). For example, for [3 1 2], the next row is [3 4 3 2]. Beware of arithmetic overflow! In clojure (since version 1.3 in 2011), if you use an arithmetic operator like + and the result is too large to fit into a 64-bit integer, an exception is thrown. You can use +' to indicate that you would rather overflow into Clojure's slower, arbitrary-precision bigint.
#+begin_src clojure
(def __ )
(= (second (__ [2 3 2])) [2 5 5 2])
(= (take 5 (__ [1])) [[1] [1 1] [1 2 1] [1 3 3 1] [1 4 6 4 1]])
(= (take 2 (__ [3 1 2])) [[3 1 2] [3 4 3 2]])
(= (take 100 (__ [2 4 2])) (rest (take 101 (__ [2 2]))))
#+end_src
* 148. The Big Divide
Write a function which calculates the sum of all natural numbers under _n_ (first argument) which are evenly divisible by at least one of _a_ and _b_ (second and third argument). Numbers _a_ and _b_ are guaranteed to be [coprimes]("http://en.wikipedia.org/wiki/Coprime").  Note: Some test cases have a very large _n_, so the most obvious solution will exceed the time limit.
#+begin_src clojure
(def __ )
(= 0 (__ 3 17 11))
(= 23 (__ 10 3 5))
(= 233168 (__ 1000 3 5))
(= "2333333316666668" (str (__ 100000000 3 5)))
(= "110389610389889610389610"
  (str (__ (* 10000 10000 10000) 7 11)))
(= "1277732511922987429116"
  (str (__ (* 10000 10000 10000) 757 809)))
(= "4530161696788274281"
  (str (__ (* 10000 10000 1000) 1597 3571)))
#+end_src
* 150. Palindromic Numbers
A palindromic number is a number that is the same when written forwards or backwards (e.g., 3, 99, 14341).  Write a function which takes an integer `n`, as its only argument, and returns an increasing lazy sequence of all palindromic numbers that are not less than `n`.  The most simple solution will exceed the time limit!
#+begin_src clojure
(def __ )
(= (take 26 (__ 0))
   [0 1 2 3 4 5 6 7 8 9 
    11 22 33 44 55 66 77 88 99 
    101 111 121 131 141 151 161])
(= (take 16 (__ 162))
   [171 181 191 202 
    212 222 232 242 
    252 262 272 282 
    292 303 313 323])
(= (take 6 (__ 1234550000))
   [1234554321 1234664321 1234774321 
    1234884321 1234994321 1235005321])
(= (first (__ (* 111111111 111111111)))
   (* 111111111 111111111))
(= (set (take 199 (__ 0)))
   (set (map #(first (__ %)) (range 0 10000))))
(= true 
   (apply < (take 6666 (__ 9999999))))
(= (nth (__ 0) 10101)
   9102019)
#+end_src
* 152. Latin Square Slicing
 A [Latin square]("http://en.wikipedia.org/wiki/Latin_square") of order `n`  is an `n x n` array that contains `n` different elements,  each occurring exactly once in each row, and exactly once in each column.  For example, among the following arrays _only the first one_ forms a Latin square: 
```

A B C    A B C    A B C
B C A    B C A    B D A
C A B    C A C    C A B
```

   Let `V` be a vector of such vectors<sup>1</sup> that they may differ in length<sup>2</sup>. We will say that an arrangement of vectors of `V` in consecutive rows  is an _alignment (of vectors) of_ `V` if the following conditions are satisfied: 


 
- All vectors of `V` are used. 
- Each row contains just one vector. 
- The order of `V` is preserved. 
- All vectors of maximal length are horizontally aligned each other. 
- If a vector is not of maximal length then all its elements are aligned  with elements of some [subvector]("http://clojuredocs.org/clojure_core/clojure.core/subvec")  of a vector of maximal length. 

 Let `L` denote a Latin square of order 2 or greater. We will say that `L` _is included_ in `V` or  that `V` _includes_ `L` iff there exists an alignment of `V`  such that contains a subsquare that is equal to `L`.   For example, if `V` equals `[[1 2 3][2 3 1 2 1][3 1 2]]`  then there are nine alignments of `V` (brackets omitted): 
```
 
        1              2              3

      1 2 3          1 2 3          1 2 3
  A   2 3 1 2 1    2 3 1 2 1    2 3 1 2 1
      3 1 2        3 1 2        3 1 2

      1 2 3          1 2 3          1 2 3
  B   2 3 1 2 1    2 3 1 2 1    2 3 1 2 1
        3 1 2        3 1 2        3 1 2

      1 2 3          1 2 3          1 2 3
  C   2 3 1 2 1    2 3 1 2 1    2 3 1 2 1
          3 1 2        3 1 2        3 1 2
```

 Alignment **A1** contains Latin square `[[1 2 3][2 3 1][3 1 2]]`,  alignments **A2, A3, B1, B2, B3** contain no Latin squares, and alignments **C1, C2, C3** contain `[[2 1][1 2]]`. Thus in this case `V` includes one Latin square of order 3  and one of order 2 which is included three times.   Our aim is to implement a function which accepts a vector of vectors `V` as an argument,  and returns a map which keys and values are integers.  Each key should be the order of a Latin square included in `V`,  and its value a count of _different_ Latin squares of that order included in `V`.  If `V` does not include any Latin squares an empty map should be returned. In the previous example the correct output of such a function is {3 1, 2 1} and _not_ {3 1, 2 3}.   <sup>1</sup> Of course, we can consider sequences instead of vectors.    
 <sup>2</sup> Length of a vector is the number of elements in the vector. 
#+begin_src clojure
(def __ )
(= (__ '[[A B C D]
         [A C D B]
         [B A D C]
         [D C A B]])
   {})
(= (__ '[[A B C D E F]
         [B C D E F A]
         [C D E F A B]
         [D E F A B C]
         [E F A B C D]
         [F A B C D E]])
   {6 1})
(= (__ '[[A B C D]
         [B A D C]
         [D C B A]
         [C D A B]])
   {4 1, 2 4})
(= (__ '[[B D A C B]
         [D A B C A]
         [A B C A B]
         [B C A B C]
         [A D B C A]])
   {3 3})
(= (__ [  [2 4 6 3]
        [3 4 6 2]
          [6 2 4]  ])
   {})
(= (__ [[1]
        [1 2 1 2]
        [2 1 2 1]
        [1 2 1 2]
        []       ])
   {2 2})
(= (__ [[3 1 2]
        [1 2 3 1 3 4]
        [2 3 1 3]    ])
   {3 1, 2 2})
(= (__ [[8 6 7 3 2 5 1 4]
        [6 8 3 7]
        [7 3 8 6]
        [3 7 6 8 1 4 5 2]
              [1 8 5 2 4]
              [8 1 2 4 5]])
   {4 1, 3 1, 2 7})
#+end_src
* 153. Pairwise Disjoint Sets
  Given a set of sets, create a function which returns `true`  if no two of those sets have any elements in common<sup>1</sup> and `false` otherwise.  Some of the test cases are a bit tricky, so pay a little more attention to them.     <sup>1</sup>Such sets are usually called _pairwise disjoint_ or _mutually disjoint_.  
#+begin_src clojure
(def __ )
(= (__ #{#{\U} #{\s} #{\e \R \E} #{\P \L} #{\.}})
   true)
(= (__ #{#{:a :b :c :d :e}
         #{:a :b :c :d}
         #{:a :b :c}
         #{:a :b}
         #{:a}})
   false)
(= (__ #{#{[1 2 3] [4 5]}
         #{[1 2] [3 4 5]}
         #{[1] [2] 3 4 5}
         #{1 2 [3 4] [5]}})
   true)
(= (__ #{#{'a 'b}
         #{'c 'd 'e}
         #{'f 'g 'h 'i}
         #{''a ''c ''f}})
   true)
(= (__ #{#{'(:x :y :z) '(:x :y) '(:z) '()}
         #{#{:x :y :z} #{:x :y} #{:z} #{}}
         #{'[:x :y :z] [:x :y] [:z] [] {}}})
   false)
(= (__ #{#{(= "true") false}
         #{:yes :no}
         #{(class 1) 0}
         #{(symbol "true") 'false}
         #{(keyword "yes") ::no}
         #{(class '1) (int \0)}})
   false)
(= (__ #{#{distinct?}
         #{#(-> %) #(-> %)}
         #{#(-> %) #(-> %) #(-> %)}
         #{#(-> %) #(-> %) #(-> %)}})
   true)
(= (__ #{#{(#(-> *)) + (quote mapcat) #_ nil}
         #{'+ '* mapcat (comment mapcat)}
         #{(do) set contains? nil?}
         #{, , , #_, , empty?}})
   false)
#+end_src
* 156. Map Defaults
When retrieving values from a map, you can specify default values in case the key is not found:  
<br/>

(= 2 (:foo {:bar 0, :baz 1} 2))  
<br/>

However, what if you want the map itself to contain the default values?  Write a function which takes a default value and a sequence of keys and constructs a map.
#+begin_src clojure
(def __ )
(= (__ 0 [:a :b :c]) {:a 0 :b 0 :c 0})
(= (__ "x" [1 2 3]) {1 "x" 2 "x" 3 "x"})
(= (__ [:a :b] [:foo :bar]) {:foo [:a :b] :bar [:a :b]})
#+end_src
* 157. Indexing Sequences
Transform a sequence into a sequence of pairs containing the original elements along with their index.
#+begin_src clojure
(def __ )
(= (__ [:a :b :c]) [[:a 0] [:b 1] [:c 2]])
(= (__ [0 1 3]) '((0 0) (1 1) (3 2)))
(= (__ [[:foo] {:bar :baz}]) [[[:foo] 0] [{:bar :baz} 1]])
#+end_src
* 158. Decurry
Write a function that accepts a curried function of unknown arity _n_.  Return an equivalent function of _n_ arguments.   
 You may wish to read [this]("http://en.wikipedia.org/wiki/Currying").
#+begin_src clojure
(def __ )
(= 10 ((__ (fn [a]
             (fn [b]
               (fn [c]
                 (fn [d]
                   (+ a b c d))))))
       1 2 3 4))
(= 24 ((__ (fn [a]
             (fn [b]
               (fn [c]
                 (fn [d]
                   (* a b c d))))))
       1 2 3 4))
(= 25 ((__ (fn [a]
             (fn [b]
               (* a b))))
       5 5))

#+end_src
* 161. Subset and Superset
Set A is a subset of set B, or equivalently B is a superset of A, if A is "contained" inside B. A and B may coincide.
#+begin_src clojure
(def __ )
(clojure.set/superset? __ #{2})
(clojure.set/subset? #{1} __)
(clojure.set/superset? __ #{1 2})
(clojure.set/subset? #{1 2} __)
#+end_src
* 162. Logical falsity and truth
In Clojure, only nil and false represent the values of logical falsity in conditional tests - anything else is logical truth.
#+begin_src clojure
(def __ )
(= __ (if-not false 1 0))
(= __ (if-not nil 1 0))
(= __ (if true 1 0))
(= __ (if [] 1 0))
(= __ (if [0] 1 0))
(= __ (if 0 1 0))
(= __ (if 1 1 0))
#+end_src
* 164. Language of a DFA
A [deterministic finite automaton (DFA)]("http://en.wikipedia.org/wiki/Deterministic_finite_automaton") is an abstract machine that recognizes a [regular language](" http://en.wikipedia.org/wiki/Regular_language"). Usually a DFA is defined by a 5-tuple, but instead we'll use a map with 5 keys:  


 
- <var>:states</var> is the set of states for the DFA. 
- <var>:alphabet</var> is the set of symbols included in the language recognized by the DFA.  
- <var>:start</var> is the start state of the DFA.  
- <var>:accepts</var> is the set of accept states in the DFA.  
- <var>:transitions</var> is the transition function for the DFA, mapping <var>:states</var> &#x2a2f <var>:alphabet</var> onto <var>:states</var>. 

  Write a function that takes as input a DFA definition (as described above) and returns a sequence enumerating all strings in the language recognized by the DFA.  Note: Although the DFA itself is finite and only recognizes finite-length strings it can still recognize an infinite set of finite-length strings. And because stack space is finite, make sure you don't get stuck in an infinite loop that's not producing results every so often!
#+begin_src clojure
(def __ )
(= #{"a" "ab" "abc"}
   (set (__ '{:states #{q0 q1 q2 q3}
              :alphabet #{a b c}
              :start q0
              :accepts #{q1 q2 q3}
              :transitions {q0 {a q1}
                            q1 {b q2}
                            q2 {c q3}}})))

(= #{"hi" "hey" "hello"}
   (set (__ '{:states #{q0 q1 q2 q3 q4 q5 q6 q7}
              :alphabet #{e h i l o y}
              :start q0
              :accepts #{q2 q4 q7}
              :transitions {q0 {h q1}
                            q1 {i q2, e q3}
                            q3 {l q5, y q4}
                            q5 {l q6}
                            q6 {o q7}}})))
(= (set (let [ss "vwxyz"] (for [i ss, j ss, k ss, l ss] (str i j k l))))
   (set (__ '{:states #{q0 q1 q2 q3 q4}
              :alphabet #{v w x y z}
              :start q0
              :accepts #{q4}
              :transitions {q0 {v q1, w q1, x q1, y q1, z q1}
                            q1 {v q2, w q2, x q2, y q2, z q2}
                            q2 {v q3, w q3, x q3, y q3, z q3}
                            q3 {v q4, w q4, x q4, y q4, z q4}}})))
(let [res (take 2000 (__ '{:states #{q0 q1}
                           :alphabet #{0 1}
                           :start q0
                           :accepts #{q0}
                           :transitions {q0 {0 q0, 1 q1}
                                         q1 {0 q1, 1 q0}}}))]
  (and (every? (partial re-matches #"0*(?:10*10*)*") res)
       (= res (distinct res))))
(let [res (take 2000 (__ '{:states #{q0 q1}
                           :alphabet #{n m}
                           :start q0
                           :accepts #{q1}
                           :transitions {q0 {n q0, m q1}}}))]
  (and (every? (partial re-matches #"n*m") res)
       (= res (distinct res))))
(let [res (take 2000 (__ '{:states #{q0 q1 q2 q3 q4 q5 q6 q7 q8 q9}
                           :alphabet #{i l o m p t}
                           :start q0
                           :accepts #{q5 q8}
                           :transitions {q0 {l q1}
                                         q1 {i q2, o q6}
                                         q2 {m q3}
                                         q3 {i q4}
                                         q4 {t q5}
                                         q6 {o q7}
                                         q7 {p q8}
                                         q8 {l q9}
                                         q9 {o q6}}}))]
  (and (every? (partial re-matches #"limit|(?:loop)+") res)
       (= res (distinct res))))

#+end_src
* 166. Comparisons
For any orderable data type it's possible to derive all of the basic comparison operations (&lt;, &le;, =, &ne;, &ge;, and &gt;) from a single operation (any operator but = or &ne; will work). Write a function that takes three arguments, a <var>less than</var> operator for the data and two items to compare. The function should return a keyword describing the relationship between the two items. The keywords for the relationship between <var>x</var> and <var>y</var> are as follows:  


 
- <var>x</var> = <var>y</var> &rarr; :eq 
- <var>x</var> &gt; <var>y</var> &rarr; :gt 
- <var>x</var> &lt; <var>y</var> &rarr; :lt 


#+begin_src clojure
(def __ )
(= :gt (__ < 5 1))
(= :eq (__ (fn [x y] (< (count x) (count y))) "pear" "plum"))
(= :lt (__ (fn [x y] (< (mod x 5) (mod y 5))) 21 3))
(= :gt (__ > 0 2))

#+end_src
* 168. Infinite Matrix
 In what follows, `m`, `n`, `s`, `t`  denote nonnegative integers, `f` denotes a function that accepts two  arguments and is defined for all nonnegative integers in both arguments.    In mathematics, the function `f` can be interpreted as an infinite  [matrix]("http://en.wikipedia.org/wiki/Matrix_%28mathematics%29") with infinitely many rows and columns that, when written, looks like an ordinary  matrix but its rows and columns cannot be written down completely, so are terminated  with ellipses. In Clojure, such infinite matrix can be represented  as an infinite lazy sequence of infinite lazy sequences,  where the inner sequences represent rows.    Write a function that accepts 1, 3 and 5 arguments 


 
-  with the argument `f`, it returns the infinite matrix **A**   that has the entry in the `i`-th row and the `j`-th column  equal to `f(i,j)` for `i,j = 0,1,2,...`; 
-  with the arguments `f`, `m`, `n`, it returns  the infinite matrix **B** that equals the remainder of the matrix **A**  after the removal of the first `m` rows and the first `n` columns; 
-  with the arguments `f`, `m`, `n`, `s`, `t`, it returns the finite s-by-t matrix that consists of the first t entries of each of the first  `s` rows of the matrix **B** or, equivalently, that consists of the first s entries  of each of the first `t` columns of the matrix **B**. 

 
#+begin_src clojure
(def __ )
(= (take 5 (map #(take 6 %) (__ str)))
   [["00" "01" "02" "03" "04" "05"]
    ["10" "11" "12" "13" "14" "15"]
    ["20" "21" "22" "23" "24" "25"]
    ["30" "31" "32" "33" "34" "35"]
    ["40" "41" "42" "43" "44" "45"]])
(= (take 6 (map #(take 5 %) (__ str 3 2)))
   [["32" "33" "34" "35" "36"]
    ["42" "43" "44" "45" "46"]
    ["52" "53" "54" "55" "56"]
    ["62" "63" "64" "65" "66"]
    ["72" "73" "74" "75" "76"]
    ["82" "83" "84" "85" "86"]])
(= (__ * 3 5 5 7)
   [[15 18 21 24 27 30 33]
    [20 24 28 32 36 40 44]
    [25 30 35 40 45 50 55]
    [30 36 42 48 54 60 66]
    [35 42 49 56 63 70 77]])
(= (__ #(/ % (inc %2)) 1 0 6 4)
   [[1/1 1/2 1/3 1/4]
    [2/1 2/2 2/3 1/2]
    [3/1 3/2 3/3 3/4]
    [4/1 4/2 4/3 4/4]
    [5/1 5/2 5/3 5/4]
    [6/1 6/2 6/3 6/4]])
(= (class (__ (juxt bit-or bit-xor)))
   (class (__ (juxt quot mod) 13 21))
   (class (lazy-seq)))
(= (class (nth (__ (constantly 10946)) 34))
   (class (nth (__ (constantly 0) 5 8) 55))
   (class (lazy-seq)))
(= (let [m 377 n 610 w 987
         check (fn [f s] (every? true? (map-indexed f s)))
         row (take w (nth (__ vector) m))
         column (take w (map first (__ vector m n)))
         diagonal (map-indexed #(nth %2 %) (__ vector m n w w))]
     (and (check #(= %2 [m %]) row)
          (check #(= %2 [(+ m %) n]) column)
          (check #(= %2 [(+ m %) (+ n %)]) diagonal)))
   true)
#+end_src
* Intervals
Write a function that takes a sequence of integers and returns a sequence of "intervals".  Each interval is a a vector of two integers, start and end, such that all integers between start and end (inclusive) are contained in the input sequence.
#+begin_src clojure
(def __ )
(= (__ [1 2 3]) [[1 3]])
(= (__ [10 9 8 1 2 3]) [[1 3] [8 10]])
(= (__ [1 1 1 1 1 1 1]) [[1 1]])
(= (__ []) [])
(= (__ [19 4 17 1 3 10 2 13 13 2 16 4 2 15 13 9 6 14 2 11])
       [[1 4] [6 6] [9 11] [13 17] [19 19]])

#+end_src
* Intro to Destructuring 2
Sequential destructuring allows you to bind symbols to parts of sequential things (vectors, lists, seqs, etc.): [(let [bindings* ] exprs*)]("http://clojure.org/special_forms#Special Forms--(let [bindings* ] exprs*)")  Complete the bindings so all let-parts evaluate to 3.
#+begin_src clojure
(def __ )
(= 3
  (let [[__] [+ (range 3)]] (apply __))
  (let [[[__] b] [[+ 1] 2]] (__ b))
  (let [[__] [inc 2]] (__)))
#+end_src
* Balancing Brackets
When parsing a snippet of code it's often a good idea to do a sanity check to see if all the brackets match up. Write a function that takes in a string and returns truthy if all square [ ] round ( ) and curly { } brackets are properly paired and legally nested, or returns falsey otherwise.
#+begin_src clojure
(def __ )
(__ "This string has no brackets.")
(__ "class Test {
      public static void main(String[] args) {
        System.out.println(\"Hello world.\");
      }
    }")
(not (__ "(start, end]"))
(not (__ "())"))
(not (__ "[ { ] } "))
(__ "([]([(()){()}(()(()))(([[]]({}()))())]((((()()))))))")
(not (__ "([]([(()){()}(()(()))(([[]]({}([)))())]((((()()))))))"))
(not (__ "["))
#+end_src
* Best Hand
Following on from [Recognize Playing Cards]("http://www.4clojure.com/problem/128"), determine the best poker hand that can be made with five cards. The hand rankings are listed below for your convenience.  


 

1. Straight flush: All cards in the same suit, and in sequence 
2. Four of a kind: Four of the cards have the same rank 
3. Full House: Three cards of one rank, the other two of another rank 
4. Flush: All cards in the same suit 
5. Straight: All cards in sequence (aces can be high or low, but not both at once) 
6. Three of a kind: Three of the cards have the same rank 
7. Two pair: Two pairs of cards have the same rank 
8. Pair: Two cards have the same rank 
9. High card: None of the above conditions are met 


#+begin_src clojure
(def __ )
(= :high-card (__ ["HA" "D2" "H3" "C9" "DJ"]))
(= :pair (__ ["HA" "HQ" "SJ" "DA" "HT"]))
(= :two-pair (__ ["HA" "DA" "HQ" "SQ" "HT"]))
(= :three-of-a-kind (__ ["HA" "DA" "CA" "HJ" "HT"]))
(= :straight (__ ["HA" "DK" "HQ" "HJ" "HT"]))
(= :straight (__ ["HA" "H2" "S3" "D4" "C5"]))
(= :flush (__ ["HA" "HK" "H2" "H4" "HT"]))
(= :full-house (__ ["HA" "DA" "CA" "HJ" "DJ"]))
(= :four-of-a-kind (__ ["HA" "DA" "CA" "SA" "DJ"]))
(= :straight-flush (__ ["HA" "HK" "HQ" "HJ" "HT"]))

#+end_src
* Parentheses... Again
In a family of languages like Lisp, having balanced parentheses is a defining feature of the language. Luckily, Lisp has almost no syntax, except for these "delimiters" -- and that hardly qualifies as "syntax", at least in any useful computer programming sense.  It is not a difficult exercise to find all the combinations of well-formed parentheses if we only have N pairs to work with. For instance, if we only have 2 pairs, we only have two possible combinations: "()()" and "(())". Any other combination of length 4 is ill-formed. Can you see why?   Generate all possible combinations of well-formed parentheses of length `2n` (n pairs of parentheses). For this problem, we only consider '(' and ')', but the answer is similar if you work with only {} or only [].  There is an interesting pattern in the numbers!
#+begin_src clojure
(def __ )
(= [#{""} #{"()"} #{"()()" "(())"}] (map (fn [n] (__ n)) [0 1 2]))
(= #{"((()))" "()()()" "()(())" "(())()" "(()())"} (__ 3))
(= 16796 (count (__ 10)))
(= (nth (sort (filter #(.contains ^String % "(()()()())") (__ 9))) 6) "(((()()()())(())))")
(= (nth (sort (__ 12)) 5000) "(((((()()()()()))))(()))")
#+end_src
* 5. Lists: conj
When operating on a list, the conj function will return a new list with one or more items "added" to the front. Note that there are two test cases, but you are expected to supply only one answer, which will cause all the tests to pass.
#+begin_src clojure
(def __ )
(= __ (conj '(2 3 4) 1))
(= __ (conj '(3 4) 2 1))
#+end_src